### ISSUE TITLE
As a developer, I want to know more about OpenLayers, so that I can understand better its performance

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#10]
**Description**
We need to better understand: what are the limits of the OpenLayers library?  We've heard anecdotally in a few places that these are the particular concerns:
    * Developer usability 
    * Rendering/performance
    * Accessibility

**Solution**
Let's do a short, time-boxed investigation where we tweak specific parameters and get better measurements to better inform our understanding of the library. 

**Describe alternatives you've considered**
We will keep this decision time-boxed, rather than going too far after having chosen a particular tool to go back. 

**Links to user research or other resources**
* Our current FE tool [analysis](https://github.com/usds/justice40-tool/pull/8) goes into some detail here but we need to flesh out the particulars and see how they apply to our specific use case. 
* Our current Gatsby [branch](https://github.com/usds/justice40-tool/commit/7e8f07c62b4756ae464cbbaab64fcbba7c3d7744) with an existing Proof Of Concept OpenLayers implementation

**Tasks**
- [x] Mapbox styles plugin - does this improve usability / interoperability
- [x] Research WebGL support : there's a beta that puts back webGL support, also older versions; do these improve things?
- [x] Measure different combinations of raster / vector 
- [x] Use Chrome DevTools and/or Puppeteer to do a basic render sanity check / comparison
- [x] Use VoiceOver to test comparative accessibility 
- [x] Understand possible react support / wrappers
- [x] Understand user interaction difficulty

**Definition of "Done"**
- [x] Comparative performance analysis (at least OL + MB)
- [x] Comparative accessibility analysis (at least OL + MB)
- [x] Working prototype with above modifications in place
- [x] Documented WebGL support specifics
