### ISSUE TITLE
As a developer, I want write access to the hosting infrastructure so that I can create the resources I need.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#101]
**Description**

**Solution**

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [x] Set up convo with Joel
- [x] During Monday meeting, ask team for overview/screenshare of the data pipeline and RDS configuration
- [x] Write access to backend infrastructure

**Definition of "Done"**
- [ ] We have control over deployment for backend infrastructure

**Comment by switzersc-usds** [comment]
Still need lambda access and any other access for processing.

**Comment by NatHillardUSDS** [comment]
Our individual accounts have read/write/update on s3, lambda, cloudfront config, and ecs ; we also have a single IAM role which can only update s3 content.

We will need dedicated and more-scoped roles for each of the upcoming tasks longer term which we don’t yet have  - chicken and egg though, in that we’d need to create the resources to know how to scope them.

Closing this ticket for now, we will handle scoping with https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/180

**Comment by NatHillardUSDS** [comment]
Our individual accounts have read/write/update on s3, lambda, cloudfront config, and ecs ; we also have a single IAM role which can only update s3 content.

We will need dedicated and more-scoped roles for each of the upcoming tasks longer term which we don’t yet have  - chicken and egg though, in that we’d need to create the resources to know how to scope them.

Closing this ticket for now, we will handle scoping with https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/180

**Comment by NatHillardUSDS** [comment]
Our individual accounts have read/write/update on s3, lambda, cloudfront config, and ecs ; we also have a single IAM role which can only update s3 content.

We will need dedicated and more-scoped roles for each of the upcoming tasks longer term which we don’t yet have  - chicken and egg though, in that we’d need to create the resources to know how to scope them.

Closing this ticket for now, we will handle scoping with https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/180
