### ISSUE TITLE
As a developer, I want to visualize ACS demographic data on my map.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#102]
**Description**
This is similar to #100, in that we need to use the most recent ACS data to visualize demographic indicators at the block group level on the map. Start with the following and we will adjust or add after we meet with advisor group:

- [ ] % Poverty
- [ ] % Less than high-school education

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Ask EJScreen for their scripts on these for reference
- [ ] Process this data and make available in a usable format, ideally on geoplatform server

**Definition of "Done"**
- [ ] View ACS demographic indicators on the map at the census block group level (locally or in prod)

**Comment by switzersc-usds** [comment]
Open question: Do the Census Block Groups in the most recent ACS correspond to the CBGs in the 2010 TIGER data? How frequently do these boundaries change?

**Comment by mikelmaron** [comment]
@switzersc-usds Census geographies are updated every 10 years, with completion of the decennial census https://2020census.gov/en/news-events/press-releases/2020-census-geographic-products.html

The TIGER/Line files for 2020 can be found at https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html

**Comment by switzersc-usds** [comment]
Thanks @mikelmaron !

**Comment by switzersc-usds** [comment]
This will involve joining the ACS data with the CBG data in the geojson.

**Comment by esfoobar-usds** [comment]
I need guidance of which columns represent the required values from the [column list here](https://docs.google.com/spreadsheets/d/1dxQug_eQH-vp9sIQDIr-iNEQx5xnXPL3/edit#gid=7913018) for both:

- 200% federal poverty level
- Racial segregation

/cc @lucasmbrown-usds @switzersc-usds

**Comment by esfoobar-usds** [comment]
From @lucasmbrown-usds:
LESSHS	count of individuals age 25 or over with less than high school degree
LOWINCPCT	% low-income

Also from the [column description file](https://docs.google.com/spreadsheets/d/1dxQug_eQH-vp9sIQDIr-iNEQx5xnXPL3/edit#gid=7913018):
ACSTOTPOP  Total

**Comment by switzersc-usds** [comment]
We're able to merge the data but it's not ready to be demoed yet.
