### ISSUE TITLE
As a user, I want to download the current version of the CBG list, so that I can see how all communities including my own stack up. (Front-end only)

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#111]
**Description**
We need a way to share the full list of census block groups so that we can begin getting user feedback. 

Excel file should include at minimum: CBG ID, impact score, each indicator score, county, state, and YES/NO in the prioritization list. 

This refers to the text/visual list of identified communities (currently one and the same as CBG) at the census block group level. Community does not equal census block group, but we are using census block group as the smallest unit of identification in the first iteration of this tool because of the data available to us.

Open questions: 
- [x] What endpoint provides this list? Is this on geoplatform? -- S3
- [x] How are we versioning the list? Punting this to another convo, other than figuring out how to pull latest CSV

**Solution**
A version of the "Download packet" (packet = .zip containing an explainer PDF and the list file) design where there's a button for an Excel version of the packet, and a button for the .csv version. @KameronKerger to confirm and update design.
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/a3ded5a4-0387-4e9e-81b1-ed840c23d46d)

**Describe alternatives you've considered**

**Links to user research or other resources**
See [how_to_download.pdf](https://app.zenhub.com/files/358242767/6741be00-9cca-4343-a683-bbcb422fd80c/download) Kameron created to illustrate how downloading and unzipping the packet would work - it's straightforward, but still including to ensure it's clear.

**Tasks**
- [x] This data available as zipped CSV on our S3 bucket (ideally our prod resources are up, if not we can send the CSV manually to S3)
- [ ] Make sure code pulls most recent CSV - ID or hash? Use S3 Versioning?
- [ ] Create the button
- [ ] Dependent on decision for threshold (as a default we will do 10% pending decision)
- [ ] Tests!!!

**Definition of "Done"**
- [ ] User visits tool and downloads a zip file with a compressed CSV of identified communities based on the current iteration of the scoring methodology.

**Comment by switzersc-usds** [comment]
Note: This needs some work with design on how to display census block groups eg with county names. Current designs use city.

**Comment by switzersc-usds** [comment]
Next step: Dev to do some research on data that's available and then sync with design to update mockup.

**Comment by katherinedm-usds** [comment]
Download of the CBG list as a .csv is not priority for Sprint 2 but is for Sprint 3. 

I think the note from Monday June 14th no longer applies, after our meeting earlier we aligned on not needing a table displayed in the site for end-July

**Comment by katherinedm-usds** [comment]
Closing as duplicate of https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/248

**Comment by katherinedm-usds** [comment]
I unfortunately closed this earlier this week on accident. There's no duplicate issue. Downloading the CBG list is still needed for Sprint 3.

**Comment by katherinedm-usds** [comment]
[https://app.zenhub.com/files/358242767/6741be00-9cca-4343-a683-bbcb422fd80c/download](https://app.zenhub.com/files/358242767/6741be00-9cca-4343-a683-bbcb422fd80c/download)

**Comment by vim-usds** [comment]
#### Defining components from the mock
To facilitate front end design / dev asynchronous discussions, thought some quick definitions would help. The term _text box_ will refer to the area shown in blue, while the term _download box_ will refer to the area in magenta:

![Screenshot at Jul 02 13-56-28.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/07cf4602-d3a5-4616-84af-328dd52209df)

#### Design questions
1. The section under question for this ticket, has a header/title labeled "Just Progress communities". Is this header/title still applicable after adding the download box? Totally might be, just wondering. 

#### Design assumptions
1. It's assumed that the current mock is showing the largest width for both the text box and the download box, if screen sizes are very large, these boxes should stay relatively the same size as we see in the mock (WYSIWYG)
2. For screen size that are considerably smaller (tablet), the text box will shrink, but download box will not. On mobile, the download box will appear under the text box.
3. In the text box, the newly added link to the Methodology page will open in the same tab.  

#### Dev things I'm thinking about
1. How can we reference a global scss variable from global.scss into a component-level scss file? Looking to globalize the primary color.
    1. Understand how the `componentName.module.scss.d.ts` really works as this might shed light to the above.
2. Should we use the `class=usa-prose` to keep section styles in alignment? Was there a reason it wasn't used on the "explore the tool" page? One immediate styling difference is the `line-height`.
3. Getting a better understanding of the backend processing will help the API design for this component.

#### Front end status
- [ ] Basic implementation of static CSS
- [ ] Make download button functional
- [ ] _Componentize_ the download box 
- [ ] Add unit tests

**Comment by vim-usds** [comment]
#### Front end status
- [ ] ~Basic implementation of static CSS~
- [ ] ~Make download button functional~
- [ ] ~Componentize the download box~ 
- [ ] ~Add unit tests~
- [ ] Add e2e tests

**Comment by switzersc-usds** [comment]
We are using a manually uploaded CSV for now and have a separate backend ticket for creating the CSV and uploading to S3 automatically.

**Comment by vim-usds** [comment]
This ticket can be reviewed at

https://usds.github.io/justice40-tool/51e6cc/en/cejst#3/33.19/-116.33

Looking forward to any feedback or improvements!

**Comment by KameronKerger** [comment]
Some minor elements to be updated including:
* No underline on button link
* Icon is black not the navy color
Additional styling elements to be covered in the styling fixes spreadsheet and updated during the "styling fixes" ticket.
* Did find a bug on Safari where the download was not occurring as expected (loaded in browser and didn't download)

**Comment by vim-usds** [comment]
Hi @KameronKerger and @janelien,

Thanks for the feedback. The styling corrections are [here](https://usds.github.io/justice40-tool/e0aa97/en/cejst/#3/33.19/-116.33).

For more information around the safari click see [here](https://gist.github.com/vim-usds/bf790146bf703596dfdb64f4ae8b4235).

I'll reach out over slack to find a time to discuss how we should move forward. Thank you!

**Comment by switzersc-usds** [comment]
Given styles are fixed and there is a proposed path forward for the safari in the doc linked above (Move forward with right click access, and on Safari just open the file in another tab), I would advocate let's do this and call this done. If this is not good enough to design for the safari piece, please create a bug that we can discuss priority for.

**Comment by vim-usds** [comment]
@switzersc-usds thanks for the decision and direction on this.

**Comment by vim-usds** [comment]
After testing out the zip file, it seems that if we get usa.csv as a zip hosted on S3, we can get around the safari issues. Jorge will provide the link tomorrow.

**Comment by vim-usds** [comment]
Hello - after getting a zip file up on s3, it seems to work better in Safari.

https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/75a57f/en/cejst/#3/33.19/-116.33

It doesn't open in a new tab anymore and all file downloads will have to be zip files to make Safari happy

**Comment by KameronKerger** [comment]
given that we can host the file and the url is shown as consistent with the url the user would see and that url is accessible by government computers this issue can be closed.
