### ISSUE TITLE
[SPIKE] As an EVCM, I want to see all states and territories on the initial map load, so that I feel my community is included.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#112]
**Description**
We need to explore options for the user experience of viewing and interacting with non-continental US areas on the initial map load so that our map is inclusive and performant. Balance map usability with user needs. 

Assumes we're loading everything rather than using geolocation to load the map relative to the user's view. Can we present user with a choice?

**Solution**
TBD

**Describe alternatives you've considered**
TBD

**Links to user research or other resources**

**Tasks**
- [ ] Investigate options from Design
- [ ] Ask GG for ideas/advice

**Definition of "Done"**
- [ ] Fleshed out github issue for this feature based on the output of discovery

**Comment by switzersc-usds** [comment]
This may be impacted by the data we're trying to render or points on the map we want to load, and how those points are clustered. Also about what people expect when they first come to the site.

In NY, users asked to see the satellite view to give users more context. This also helps capture/convey proximity to sites like airports.

**Comment by mikelmaron** [comment]
I've seen a couple approaches to this.

One is to have inset maps along the bottom or side of the map. Performance is not necessarily an issue but does have UX challenges. First, they can take up a lot of room -- I've worked on maps with Alaska, Hawaii, Puerto Rico and Guam and the map felt crowded; and there are other locations to consider as well. Next, a different strategy will be needed on mobile view. Third, need to have some hard to get right logic about when to show the inset maps. They could be always on, but then it may be odd to be zoomed in on Guam, and also see Guam in the inset lists; or they could be turned off when zoomed in, but then it's not obvious how to get back to the point where there's a jump to the other locations. 

The other approach is to have a series of small buttons present near the zoom buttons. I think it's an elegant solution. This has advantage of being compact, can always be on, and is relatively extendable. [This map by datadiversitykids.org](https://www.diversitydatakids.org/maps/#/explorer/) utilizes this technique, only for continental US, Hawaii and Alaska. They also do browser geolocation -- but the approach stands alone without that I think.

![image](https://user-images.githubusercontent.com/22896/122986988-b793b380-d365-11eb-8bcf-08652b300278.png)

**Comment by switzersc-usds** [comment]
TODO make a card for making an icon for off-map territories and states that then zooms to those regions.
