### ISSUE TITLE
As an EVCM, I want to read some explanation of the scoring methodology on the Methodology page, so that I understand how my community was or was not prioritized.

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#113]
**Description**
We describe clearly to the EVCM user how the data indicators are combined into a cumulative index, as well as simple short information about the individual datasets on cards per Sprint 3 wireframes on the Methodology page.

**Solution**
How the cumulative index is calculated, as well as simple short information about the individual datasets on cards, should be implemented using Sprint 3 wireframes as guidance on the Methodology page.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [x] Link header Methodology link to new Methodology page
- [x] Scoring methodology explainer section near the top (and let Beth or Kameron know how best to deliver this content text)
- [ ] Placeholder for the data list
 
**Definition of "Done"**
 - [ ] Matches mockup

**Comment by katherinedm-usds** [comment]
I think explanation of the scoring methodology should be prioritized for Sprint 3, and having a pop up for this is lower priority than having the \methodology (or similar) page. I'll work with Design to rescope this.

**Comment by katherinedm-usds** [comment]
Updated scope of this card to reflect latest discussion and designs, focusing on Methodology page for July 27th launch

**Comment by katherinedm-usds** [comment]
@KameronKerger will update PDF today. @BethMattern has "Screening Tool Methodology - Content for Site" on shared drive - Jane will start using what's here in the meantime to start laying this out. We should make sure close to final designs are ready for Sprint 4 this Thursday

**Comment by katherinedm-usds** [comment]
The sprint 4 designs Jane provided are up to date

**Comment by switzersc-usds** [comment]
Closing as duplicate of #144 and #351
