### ISSUE TITLE
[SPIKE] As a user of the site, I want to see a table of communities below a given scoring threshold, so I can see information aggregated outside of a map context

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#116]
**Description**
Our designs have a section currently entitled "Community List", intended to be a visual list of communities that are below our 40% scoring threshold. We should investigate the feasibility of both querying and displaying this data in a tabular format.

**Solution**
Do a spike on two fronts:
1. How can we query non-geospatial information from our static website, outside of the context of our mapping library, as this will be a separate page (this may involve pre-computing/pre-storing etc, we should leave this on the table)
2. How can we display this information in a table? This involves questions like : how do we handle pagination? 

**Describe alternatives you've considered**
* Non-static website / dynamically-generated content - this would be a larger change than we'd like to make
*  Using the mapping library to query this info - this may still be an option, as we'll be doing other queries against the postgis/mbtiles servers

**Links to user research or other resources**
N/A

**Tasks**
- [ ] (Backend) Write up a proposal of how to store and query scoring information such that it could be displayed in a table outside of a map
- [ ] (Front-end / Middle-end) Write up a proposal of how to display this information in a table and how this would interface with the above server
- [ ] Create tickets to cover this / these solution(s)

**Definition of "Done"**
- [ ] We have defined how to move forward on both the frontend and backend vis-a-vis displaying tabular data (this ticket, as a spike, does not cover implementation)

**Open Questions**
* Should we pre-process data and store a geoJSON with just the score?
* Do we need dedicated middleware?
* Could we make use of a purpose-specific serverless lambda?
* What restrictions does the site being static place on us?
* If we do store this and query, can we use the GraphQL functionality built in to Gatsby?
