### ISSUE TITLE
As a developer, I want to test out different scoring methodologies with a command line tool so that I can understand and communicate differences in outputs.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#119]
**Description**
We need a simple way to combine initial indicator data sets in different ways so that we can begin analyzing and sharing the outputs of an initial scoring methodology. This tool/script should be built in a way that lets us add/remove input indicators and change the combination algorithm easily; however, that's design guidance, not a requirement for this issue. Ideally this will also be able to be easily repurposed and incorporated into our data pipeline. 

In this, we also want to learn how long the scoring compute might take (upper and lower bounds) and how frequently we may need to run this compute. 

**Solution**
Create a command line tool/script that combines our two initial demographic indicators (% Poverty, % Less than high-school education from the ACS) and outputs a list of census block group IDs.

As part of this solution, we will need to normalize the ACS data into percentiles if this is not already available as part of the data.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Specify dataset URLs for the two ACS indicators
- [ ] Find out if the data is already available with percentiles; if not, normalize the data into percentiles
- [ ] Set up scoring notebook to output list of census block groups averaging the 2 indicators
- [ ] Document calculations and decisions, eg how percentile is calculated

**Definition of "Done"**
- [ ] We have a script in our repository that enables us to combine the two ACS indicators above with at least two scoring methodologies (e.g. addition and multiplication) and output a list of census block group IDs.
- [ ] Have range estimate for compute time for score to inform architecture decision
