### ISSUE TITLE
Create a 3-state side panel to accommodate island territories

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1198]
# Purpose
The side panel will have 3 states, namely,
1. Nation
2. Puerto Rico
3. Island areas

There will be another field called UI experience that will determine which of these 3 states the UI should be in. (this will be sent by BE)

Number of thresholds is different for each case, will be a field on the tiles. (this will be sent by BE)

## Nation
- This state will be the US +  DC (current operation). This will not include the territories.
- number of thresholds = 21 (this will be sent by BE)

## PR
- This state will be when PR is selected. The UI will only display the WF category
- number of thresholds = 5 (this will be sent by BE)

## Island Areas
- This state will show the following 4 indicators in the Workforce category. No other indicators will be shown.
- number of thresholds = 4 (this will be sent by BE)

1. field_names.ISLAND_AREAS_UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD
2. field_names.ISLAND_AREAS_POVERTY_LOW_HS_EDUCATION_FIELD
3. field_names.ISLAND_AREAS_LOW_MEDIAN_INCOME_LOW_HS_EDUCATION_FIELD
4. field_names.ISLAND_AREAS_LOW_HS_EDUCATION_FIELD

### ISLAND_AREAS_UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD
- value key = IAULHSE_PFS
- boolean key = IAULHSE
- side panel indicator title = "Unemployment"
- side panel indicator description = "Number of unemployed people as a percentage of the labor force"

### ISLAND_AREAS_POVERTY_LOW_HS_EDUCATION_FIELD
- value key = IAPLHSE_PFS
- boolean key = IAPLHSE
- side panel indicator title = "Poverty"
- side panel indicator description = "Percent of a tract's population in households where the household income is at or below 100% of the federal poverty level"

### ISLAND_AREAS_LOW_MEDIAN_INCOME_LOW_HS_EDUCATION_FIELD
- value key = IALMILHSE_PFS
- boolean key = IALMILHSE
- side panel indicator title = "Low median income"
- side panel indicator description = "Median income calculated as a percent of the area’s median income"

### ISLAND_AREAS_LOW_HS_EDUCATION_FIELD
- value key = IALHE_PFS
- boolean key = IALHE
- side panel indicator title = "High school degree achievement rate"
- side panel indicator description = "Percent of people ages 25 years or older whose education level is less than a high school diploma when higher ed enrollment rate is less than 20% in order to exclude areas with college and graduate students"

# Tasks
- [x] work with backed to get all fields
- [x] build the pipeline locally to validate fields are in
- [x] integrate fields into each state
- [x] update the total number of thresholds
- [x] replace state with territory
- [x] write tests
- [x] test locally
- [x] run pipeline tests
- [x] push branch
- [ ] run pipeline on main to S3
- [ ] merge to main
- [ ] test on main

<img width="126" alt="Screen Shot 2022-01-28 at 2 41 26 PM" src="https://user-images.githubusercontent.com/86254807/151633745-4a1c18d9-cca2-4fbe-82de-b3ff987d2045.png">

**Comment by lucasmbrown-usds** [comment]
@emma-nechamkin can provide column names for #3, which will be different than column names for other workforce dev categories

**Comment by emma-nechamkin** [comment]
@vim-usds columns are:

__Percentiles for Island areas' workforce columns__
- Low ami for islands: "IAULHSE_PFS"
- Poverty for islands: "ISPLHSE_PFS"
- Unemployment for islands: "IALMILHSE_PFS"

Please let me know if this is what you need! The other two fields ("Thresholds" and "UI Experience") don't currently have short names -- if you want them to, I'm happy to make the change, please just let me know what would be helpful for you!

**Comment by vim-usds** [comment]
Will pull main and run the pipeline and on will have 5 flags

Islands 
1. experiences - nation, PR, island

Low ami for islands: "IAULHSE_PFS" - Area Median Income islands
Poverty for islands: "ISPLHSE_PFS"
Unemployment for islands: "IALMILHSE_PFS"
