### ISSUE TITLE
As a community member, I want to understand what this repo is, so that I know how to engage with it.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#12]
**Description**
When someone lands on this public repo, they need to understand what it is, who we are, why we've made this, and how they can interact with this repo or the project.

**Solution**
Add the standard OSS content: 

- [x] README
- [x] Contributing.md
- [x] Code of Conduct
- [x] License
- [x] Link to website or other public info about Justice40
- [x] Info on how to contact us

**Describe alternatives you've considered**
N/A

**Links to user research or other resources**
N/A

**Tasks**
- [x] set up public listserv

**Definition of "Done"**
* List above is complete
* We have shared the repo with this fresh content with our OSS community
