### ISSUE TITLE
Implement downloads page under Methodology and Data

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1240]
# Purpose
Need to determine design for making all of the various files available to the public
<img width="1257" alt="Screen Shot 2022-04-04 at 4 31 15 PM" src="https://user-images.githubusercontent.com/86254807/161654781-72681210-7bd4-494c-9b1a-a4431edf57e6.png">

## Tasks
High Risk
- [x] add basic side nav
- [x] mobile layout to show nested options, while desktop show side nav

Low risk:
- [x] Indent Side Nav
- [x] get links on Download page with actual sizes
- [x] test a11y
- [x] remove tab on Personal Eng button
- [x] ensure both alerts will expire on May 25th
- [x] update 3rd bullet copy after May 25th
- [x] update RFI copy to after May25th
- [x] add unit tests

**Comment by KameronKerger** [comment]
[https://app.zenhub.com/files/358242767/15e71c93-1d7f-45c9-b9ad-88a6d03518b2/download](https://app.zenhub.com/files/358242767/15e71c93-1d7f-45c9-b9ad-88a6d03518b2/download)

**Comment by KameronKerger** [comment]
[https://app.zenhub.com/files/358242767/d0ed80d0-e89c-4d68-b344-60d5370ea0e9/download](https://app.zenhub.com/files/358242767/d0ed80d0-e89c-4d68-b344-60d5370ea0e9/download)

**Comment by KameronKerger** [comment]
[downloads.pdf](https://github.com/usds/justice40-tool/files/8383693/downloads.pdf)

**Comment by vim-usds** [comment]
@esfoobar-usds - can you attach the links that should be used for the 3 links identified in the mock above? TY

**Comment by vim-usds** [comment]
@KameronKerger and/or @esfoobar-usds - do we know where the versions link is suppose to go?

**Comment by esfoobar-usds** [comment]
- [Excel](https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/downloadable/communities-2022-03-30-0033GMT.xlsx)
- [CSV](https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/downloadable/communities-2022-03-30-0033GMT.csv)
- [Shapefile](https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/shapefile/usa.zip)

Do not add the change log link -- that is for when we have versioning turned on. Correct me if I'm wrong please @BethMattern.

**Comment by vim-usds** [comment]
@KameronKerger thanks for the demo today! If above mock is not the latest, can you update that here?

Tasks:

- remove do wnload box
- create the download page
- have alerts expire by May 25th
- breadcrumb
- no version accordion (for now)

**Comment by KameronKerger** [comment]
pages we discussed yesterday @vim-usds - caveats:
* no change log necessary at this time
* the sizes are placeholders, will need to get actual file sizes
* the header being no longer beta is only for once 1.0 is released
* no need for previous versions yet
![Downloads_new_pages](https://user-images.githubusercontent.com/77702996/169111638-1a5e0c42-531f-46b7-841a-3628e550280f.png)
![Methodology_new_pages](https://user-images.githubusercontent.com/77702996/169111649-9b4e9e90-acc9-4f78-a360-5cdeea6268f6.png)

**Comment by vim-usds** [comment]
![Screen Shot 2022-05-24 at 1 55 08 PM](https://user-images.githubusercontent.com/86254807/170132388-7d998ca0-ba27-4934-8ed3-3dfd82c37727.png)
