### ISSUE TITLE
Implement the side panel to make the formula more apparent

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1311]
# Purpose
Update sidepanel to match mock:
![Screen Shot 2022-02-22 at 1 13 44 PM](https://user-images.githubusercontent.com/86254807/155235005-b2620bfb-4b66-4c21-871b-4349b515f6c6.png)

## Task list ExceedBurden and AND components
- [x] create new component for Exceed text
- [x] add AND spacer, push into container
- [x] have burdens push into parent container
- [x] determine which fields will be coming from the BE
- [x] create BE ticket for Emma
- [x] intl on EXCEED and AND component
- [x] hook up BE signal stubs
- [x] create/ runs tests for EXCEED and AND tests

## Tasks for new IndicatorValue component
- [ ] create a new InidicatorValue component
- [ ] hook up BE stubs
- [ ] intl
- [ ] tests

## Tasks for general testing
- [ ] ensure mobile / tablet friendly

### Should the BE send answers to burden questions?
 Should BE send the boolean value to the following two questions:
<img width="507" alt="Screen Shot 2022-02-22 at 7 16 24 PM" src="https://user-images.githubusercontent.com/86254807/155256314-45ad0d85-6bbc-4465-a297-fd5c038afe34.png">
<img width="507" alt="Screen Shot 2022-02-22 at 7 16 36 PM" src="https://user-images.githubusercontent.com/86254807/155256361-eba805fd-eb24-4f9a-880e-dea54a6e8018.png">

I can deduce Y/N values (as the BE already sends the booleans for each category so simply adding them up would allow me to figure it out), however, there's a part of me that feels that to be consistent with our architecture of all data coming from the backend, we may want to add two more booleans as the answer to each question? Thinking about this more, errors on the booleans may propagate if the FE figures it out

### Should the BE send the threshold value and direction?
<img width="519" alt="Screen Shot 2022-02-22 at 7 20 52 PM" src="https://user-images.githubusercontent.com/86254807/155256997-dd26164c-9356-4e88-99ed-2277535a6112.png">

Assumptions
1. the value sub-text's direction will be (for the near future) `above` or `below` only
2. the threshold will always be a 2 digit number followed by `th` of `%` 

Can the BE send this information on a per tile basis? This would allow us to change thresholds. Also it's OK if it's not sent as this is more of a score/methodology thing which, if it changes, will effect other parts of the site as well, ie, the methodology page.

**Comment by KameronKerger** [comment]
one change already! Meets should be Exceeds in both questions. New pitcha attached.
[Option Twoa_updated.pdf](https://github.com/usds/justice40-tool/files/8099857/Option.Twoa_updated.pdf)

**Comment by vim-usds** [comment]
@KameronKerger - thanks! Updated the main picture on this ticket

**Comment by vim-usds** [comment]
@jorge, (optional: @emma-nechamkin)

The UI calls for two questions with boolean answers:

1. Exceeds the threshold for one or more burden indicators? (Y/N)
2. Exceed the threshold for both socioeconomic indicators? (Y/N)

I can deduce Y/N values (as the BE already sends the booleans for each category so simply adding them up would allow me to figure it out), however, there's a part of me that feels that to be consistent with our architecture of all data coming from the backend, we may want to add two more booleans as the answer to each question?

What are your thoughts?

Assuming for now that the FE will figure it out.

**Comment by vim-usds** [comment]
Thinking about this more, errors on the booleans may propagate if the FE figures it out

**Comment by KameronKerger** [comment]
looking good @vim-usds

**Comment by vim-usds** [comment]
Hi @BethMattern, looking for some direction on this ticket:

After speaking with @emma-nechamkin there seems to be a few ways to move forward. This ticket requires a BE signal to complete this ticket. This BE ticket that creates this signal ([1325](https://github.com/usds/justice40-tool/issues/1325)) has been created, however it isn't in Emma current sprint as it was created mid-sprint. 

I imagine we have the following 3 ways to move forward:

1. Have the FE calculate what the BE should provide now, and whenever the BE is ready, remove this FE calculation logic and place the BE signal in. This solution implies this feature WILL be shipped this sprint.
2. Pause on this ticket until the BE is completed. This solution implies this feature will NOT be shipped this sprint.
3. Re-prioritize Emma's sprint to include ([1325](https://github.com/usds/justice40-tool/issues/1325)). This solution implies this feature COULD be shipped this sprint.

Any thoughts? TY

**Comment by BethMattern** [comment]
@KameronKerger is going to update the design to change 'exceeds' to 'at or above'
