### ISSUE TITLE
As a developer/designer, I want to understand the limitations of mapping tech and how this relates to designs, so that I can move quickly and focus on the right things

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#132]
**Description**
We have come across a number of questions so far from design about proposed upcoming specs. We should research these questions so that we can come into discussions better informed and ready to weigh in on proposed next steps

**Solution**
We should enumerate a list of questions in "tasks" below, write out our research findings in this ticket, and come back to design to discuss before specs are finalized for next sprint

**Describe alternatives you've considered**
If either dev or design goes rogue we will have unimplementable or unusable solutions.

**Links to user research or other resources**
N/A

**Tasks**
We need to answer the below questions:
- [ ] How can we make block groups more user-friendly as a concept? Can we associate a block group with a "census place" in some way? How difficult would it be do to do so? Is it sufficient to use county? 
- [ ] What is the best way to query non-geospatial information from our stored tiles and/or geoJSON given our new flat-file-first setup?
- [ ] What is the best way to represent tabular data, taking into account paging, 
- [ ] What is the best way to combine choropleth layers that cover the same geographic space? we can only really have one enabled at a time, but need to talk through implications of this with design

**Definition of "Done"**
We have written out answers to the above questions in this ticket

**Comment by switzersc-usds** [comment]
@NatHillardUSDS I see this one snuck into our sprint :P What is the status here?

**Comment by NatHillardUSDS** [comment]
I have done research on these, will post results below

**Comment by switzersc-usds** [comment]
Awesome, thank you!

**Comment by switzersc-usds** [comment]
We may also want to have a dev design sync on the answers too. Feel free to go ahead and put that on the cal for a time that makes sense :)

**Comment by switzersc-usds** [comment]
I am going to schedule this convo for Monday!

**Comment by switzersc-usds** [comment]
Conversation scheduled for tomorrow after standup.

**Comment by NatHillardUSDS** [comment]
Wrote up the answers to these and shared results with core team in sync just now, so closing this one out
