### ISSUE TITLE
See if adding an address to open street map propagates to CEJST search automatically

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1412]
A survey response has pointed out that their address `3125 Reservation Road, Weldon, CA 93283` comes up as invalid in the CEJST search.

## Tasks
- [ ] understand how to [add / update open street maps](https://opencagedata.com/tutorials/adding-an-address-to-openstreetmap)
- [ ] test the new address addition
- [ ] respond to respondent of update
- [ ] inform support team that they can send out link on how anyone can edit an address
