### ISSUE TITLE
As an EVCM, I want to see and understand any data sources used in the generation of the score and list, so that I can understand the data & methodology (FRONTEND ONLY). 

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#144]
**Description**
The need for both EVCM and agency partners is to know the provenance of the datasets and information about the scoring methodology used to calculate the cumulative index score and determine which communities are prioritized. 

**Solution**
This will require a separate Data & methodology page with a section that describes the scoring methodology and a section that shows individual cards for each dataset that is used in the latest version of the cumulative index. 

Note that this is just about getting the dataset information from the JSON and displaying it, not other design updates.

**Describe alternatives you've considered**

**Links to user research or other resources**
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/9d98b027-c819-4900-a302-5b28586396da)
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/619ce423-534a-49f6-b2c5-0e1530bc401d)

**Tasks**
- [ ] Data set info should draw on the JSON file that is generated from YAML files for datasets published in the repo
 - [ ] Ensure cards match format shown in latest sprint design which includes link to data source

**Not in scope**
 - Cards don't need to be sorted or moveable

**Definition of "Done"**
Site with date representing latest set of datasets and scoring methodology planned for 7/27 launch can be navigated on http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/f12ab4/en/cejst/ (or similar)

**Comment by katherinedm-usds** [comment]
We should make sure latest designs are ready Thursday for Sprint 4

**Comment by katherinedm-usds** [comment]
Jane has access to the Screening Tool catasets content from Beth, we won't do "why this is important" for launch.

**Comment by janelien** [comment]
Designs are shared; they're also attached to ticket #351

**Comment by switzersc-usds** [comment]
Note that we need either a sample JSON file to use or to have the backend ticket done (marked as a blocker for this one).

**Comment by vim-usds** [comment]
Proposed temporary json structure:

const data = [
 {
 title: string,
 indicator: ENUM<string>, //if less than 10
 dataResolution: string
 dataSourceLabel: string,
 dataSourceURL: string
 yearLastUpdated: number,
 note: string
 }, {...}, (...}
]

**Comment by vim-usds** [comment]
Task list:

- [ ] remove aside
- [ ] move limited data sets to below the card area
- [ ] render cards for desktop (> 1024)
- [ ] render cards for mobile (< 400 )

**Comment by vim-usds** [comment]
@janelien Initial implementation is here:

http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/935adf/en/methodology/

If this site doesn't work, the hash is `935adf` and you can place that in the correct URL. 

See ya tmrw!

**Comment by vim-usds** [comment]
@janelien, the fixes are in!

https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/8fe87c/en/methodology

If we have the green light, I can close this!
