### ISSUE TITLE
Update wording & thresholds on side panel and methodology for higher ed and high school degree 

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1441]
# Purpose
Modify copy to corresponding to flipping some indicators.

### From this
![Screen Shot 2022-03-24 at 7 02 26 AM](https://user-images.githubusercontent.com/86254807/159933260-9522c9f9-f0a9-41d6-86b7-ad2e75d6c64d.png)

### To this
![Screen Shot 2022-03-28 at 1 53 37 PM](https://user-images.githubusercontent.com/86254807/160485419-c3cfdc1c-ddeb-44e3-8767-60bce629432c.png)

### Copy
```
Higher education non-enrollment
Percent of people 15 or older who are not currently enrolled in college, university, or graduate school.

Used in: All categories 
Responsible party: Census 

Source: American Community Survey      from 2015 - 2019
Available for: All U.S. states, the District of Columbia, and Puerto Rico
```

### Tasks
- [ ] update Title
- [ ] update Description 
- [ ] update Available for

### From this
![Screen Shot 2022-03-24 at 7 07 21 AM](https://user-images.githubusercontent.com/86254807/159934304-a9f07476-8d5b-4e0b-be8a-d878fe6740d2.png)

### To this
![Screen Shot 2022-03-28 at 1 55 11 PM](https://user-images.githubusercontent.com/86254807/160485638-5d6d57db-3bd6-4e42-a4c4-fe02a5901530.png)

### Copy
```
High school degree non-attainment
Percent of people age 25 years or older in a census tract whose education level is less than a high school diploma.

Used in: Training and workforce development methodology
Responsible party: Census

Source: American Community Survey   from 2015-2019
Available for: All U.S. states, the District of Columbia and Puerto Rico

Source: American Community Survey   from 2010 
Available for: American Samoa and the Northern Mariana Islands
```

### Tasks
- [ ] update title

### From this
![Screen Shot 2022-03-24 at 7 11 54 AM](https://user-images.githubusercontent.com/86254807/159935226-a180a3a0-ecd8-45cd-ae65-b5e02726ceae.png)

### To this
![Screen Shot 2022-03-28 at 1 56 14 PM](https://user-images.githubusercontent.com/86254807/160485798-103acd4d-735b-461c-8859-eeef4e07b749.png)

### Copy
```
Training and workforce development
Communites are identified as disadvantaged in this category
IF at or above the 90th percentile for median income as a percent of area median income OR linguistic isolation OR unemployement OR percent individuals in households at or below 100% Federal poverty level
AND 10% or more of adults 25 or older have not attained a high school degree AND 80% or more of adults 15 or older are not enrolled in higher education
```

### Tasks
- [ ] update full AND

### From this
![Screen Shot 2022-03-24 at 7 15 59 AM](https://user-images.githubusercontent.com/86254807/159936549-d79d306c-221d-4aed-8c3b-ea3d2608de7c.png)

### To this
<img width="453" alt="Screen Shot 2022-03-24 at 10 54 03 AM" src="https://user-images.githubusercontent.com/77702996/159979642-43b4c074-e7b5-4f9b-a09e-a455ead34907.png">

### Tasks
- [ ] update second AND

## Question for Kameron
- In the note are you referring to the NEW TAB (recently renamed to Side Panel Copy)?
- Answer: yes, the two category names marked with yellow backgrounds need to be updated. scroll down they are at the bottom.

**Comment by KameronKerger** [comment]
[higher_ed.pdf](https://github.com/usds/justice40-tool/files/8326330/higher_ed.pdf)
[high_school.pdf](https://github.com/usds/justice40-tool/files/8326310/high_school.pdf)
[training and workforce.pdf](https://github.com/usds/justice40-tool/files/8326340/training.and.workforce.pdf)

@vim-usds see also the two side panels with a green background on the Indicators for UI and Export sheet.

**Comment by vim-usds** [comment]
@kameron will update these mocks, TY!

**Comment by vim-usds** [comment]
@emma-nechamkin (optionally @KameronKerger) - some of these mocks have now flipped the higher ed and high school to be the opposite of what they originally, ie, below 20% => above 80 %.  Does this mean that the associated BE signals (`CA`, `HSEF`, `IAHSEF`) need to be flipped and baked into a staging link? Maybe this is already done? Let me know if I'm missing something. TY!

**Comment by emma-nechamkin** [comment]
This is already done @vim-usds! See https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/1393

**Comment by vim-usds** [comment]
@emma-nechamkin - gotcha! 

I might be missing something. However here's my understanding. It seems that on the latest staging link is returning the following:

![Screen Shot 2022-03-28 at 3 33 03 PM](https://user-images.githubusercontent.com/86254807/160499559-37a7cd28-10b0-4c4e-849c-1261812828ce.png)

On step1 of the above screenshot - I have a typo, 1493 should be 1393 (the ticket mentioned in your ticket). TY!

**Comment by vim-usds** [comment]
@emma-nechamkin 

Re 4: Cool updating to NCA, TY!

For 3a - coercion is totally fine!

Also is there a boolean for NCA? Like NCA_GT80 maybe?

**Comment by emma-nechamkin** [comment]
it should be the same boolean -- the two are logically equivalent (CA_LT20 == NCA_GT80)
