### ISSUE TITLE
As a developer, I want to ingest the Air Toxics Cancer Risk data set from EJScreen, so that it can be tested as an input to the cumulative impact score.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#146]
**Description**
The Air Toxics Cancer Risk data set from EJScreen needs to be available in the screening tool so that it can be used as an input into the cumulative impact score.

This data set will eventually be displayed in the map for selected census block groups and exported in the list of communities.

The system needs to classify this data set as an "Exposure" indicator. A future version of the cumulative impact score will need this classification as part of the formula.

Both the raw value and the value converted to percentiles for the entire country must be available in the tool.

This data is  available in EJSCREEN.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Air Toxics Cancer Risk at the census block group level is available to be used as an input into the score
- [ ] Air Toxics Cancer Risk is classified as an "Exposure" indicator
- [ ] Air Toxics Cancer Risk is normalized into a percentile for the entire country
- [ ] Air Toxics Cancer Risk is available to be displayed in the map UI
- [ ] Air Toxics Cancer Risk is available to be downloaded in the CSV
