### ISSUE TITLE
As a developer, I want to use ACS data directly from Census's open data, rather than from EJScreen, so that the data pipeline is as transparent and direct as possible.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#154]
**Description**
Right now for our initial draft score we're using ACS data from EJScreen because it's easily accessible and nicely formatted. However, because their code is not open source it introduces an opaque step in our data pipeline, and our goal is to have every step of the data pipeline be open and transparent. We should investigate how to pull directly from Census's open data instead, OR work with EJscreen to open up their code that pulls and transforms the ACS data. 

**Solution**
See tasks below. Essentially, we need to investigate if we can make the EJScreen ETL of ACS open source and if not how we can access them most recent ACS summary data directly from Census.

**Describe alternatives you've considered**

**Links to user research or other resources**

From a timeboxed investigation of the ACS data on the Census website:
* raw data at the block group level from the 2013 5 year summary is available to download in a lot of zip files here: https://www2.census.gov/acs2013_5yr/summaryfile/
* you have to combine the files with an excel template in order to make sense of them in a human-readable way. see this tutorial: https://www2.census.gov/acs2013_5yr/summaryfile/ACS_SF_Excel_Import_Tool.pdf
* they can be combined programmatically without excel, but its probably necessary to do an excel version first to understand what you're looking for in order to code it properly
* notably, this is the 5 year from 2013, so not super recent. i still need to compare this with the ejscreen data to confirm whether ejscreen is using the same year or if they have more recent data.

**Tasks**
- [ ] find out what year ejscreen ACS data is from
- [ ] talk to the EJSccreen team about what they do to extract and transform the ACS data, determining if it's possible to open source this in a repo owned by them, or to use what they're doing and open source it on our repo. 
- [ ] identify best census contact to ask about getting more recent ACS data than the 2013 data available on their FTP site

**Definition of "Done"**
- [ ] We replace this opaque step in our data processing with an open step

**Comment by switzersc-usds** [comment]
Closing as done
