### ISSUE TITLE
As a developer, I want to ingest the population of the census block groups data set from EJScreen, so that it can be tested to identify disadvantaged communities

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#158]
**Description**
The population of the census block groups data set from EJScreen needs to be available in the screening tool so that it can be used as an input into the formula for determining disadvantaged communities.

This data set will eventually be displayed in the map for selected census block groups and exported in the list of communities.

This data is part of the American Community Survey (ACS) data set. It is also available in EJSCREEN.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Census block group population data is available to be used in the formula for identifying disadvantaged communities
- [ ] Census block group population data is available to be viewed in the map UI
- [ ] Census block group population data is available to be downloaded in a .csv along with other data about census block groups
