### ISSUE TITLE
As a developer I want to have a static site base to build upon

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#17]
**Description**
Following our decision around static site generators  ([here](https://github.com/usds/justice40-tool/issues/6) ), we should create a template based on this framework and commit to the repo for future iteration.

**Solution**
Use site generator to create scaffolding for a new site. 

**Describe alternatives you've considered**
See https://github.com/usds/justice40-tool/issues/6 

**Links to user research or other resources**
See above

**Tasks**
- [ ] Generate static site

**Definition of "Done"**
- [ ] Bare site scaffolding has been committed to the repo
- [ ] Localization framework/tooling set up as relevant

**Comment by switzersc-usds** [comment]
Opting to close this because it's too implementation focused and will be covered by #16
