### ISSUE TITLE
As a developer, I want to ingest the Individuals over 64 years old data set from EJScreen, so that it can be tested as an input to the cumulative impact score.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#171]
**Description**
The Individuals over 64 years old data set from EJScreen needs to be available in the screening tool so that it can be used as an input into the cumulative impact score.

This data set will eventually be displayed in the map for selected census block groups and exported in the list of communities.

The system needs to classify this data set as a "Sensitive populations" indicator. A future version of the cumulative impact score will need this classification as part of the formula.

Both the raw value and the value converted to percentiles for the entire country must be available in the tool.

This data is part of the American Community Survey (ACS) data set. It is also available in EJSCREEN.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Individuals over 64 years old at the census block group level is available to be used as an input into the score
- [ ] Individuals over 64 years old is classified as a "Sensitive populations" indicator
- [ ] Individuals over 64 years old is normalized into a percentile for the entire country
- [ ] Individuals over 64 years old is available to be displayed in the map UI
- [ ] Individuals over 64 years old is available to be downloaded in the CSV
