### ISSUE TITLE
As a developer, I want to ingest 16 data sets from the EJScreen data source, so that they can be tested as inputs to the cumulative impact score.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#176]
**Description**
The 16 different data sets from the EJScreen data source need to be available in the screening tool so that they can be used as an input into the cumulative impact score.

These data sets may eventually be displayed in the map for selected census block groups and exported in the list of communities.

The system needs to classify each data set as indicated below. A future version of the cumulative impact score will need this classification as part of the formula.

Both the raw value and the value converted to percentiles for the entire country must be available in the tool.

**Exposures:**
Air Toxics Cancer Risk
Respiratory Hazard Index
Diesel PM
Particulate Matter (PM2.5)
Ozone
Traffic Proximity and Volume

**Environmental effects:**
Proximity to RMP Sites
Proximity to TSDF Sites
Proximity to NPL Sites
Wastewater Discharge
Lead Paint

**Sensitive populations:**
Individuals under 5 years old
Individuals over 64 years old

**Socioeconomic factors:**
Linguistic Isolation
Poverty (Less than 200% of the federal poverty line)
Less than a high-school education

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Each data element is at the census block group level is available to be used as an input into the score
- [ ] Each data element is classified properly (as they are grouped above)
- [ ] Each indicator is normalized into a percentile for the entire country
- [ ] Each indicator is available to be displayed in the map UI
- [ ] Each indicator is available to be downloaded in the CSV
