### ISSUE TITLE
As a developer, I want to ingest the LEAD score data set from DOE, so that it can be included in the prioritized communities download file.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#178]
**Description**
The LEAD score data set from DOE needs to be available in the screening tool so that it can be included for all census block groups in the csv/excel download file. The LEAD score represents the percentage of gross household income that goes to pay for energy. This data is only available at the Census tract level, so completing this task is dependent on developing a methodology for applying census tract data to census block groups within a tract. 

It does include data for DC and Puerto Rico.

The source of the LEAD score is [Open Energy Data Initiative (OEDI)
](https://data.openei.org/submissions/573)

"The Low-Income Energy Affordability Data comes primarily from the 2018 U.S. Census American Community Survey 5-Year Public Use Microdata Samples and is calibrated to 2018 U.S. Energy Information Administration electric utility (Survey Form-861) and natural gas utility (Survey Form-176) data."

This data will be included in a future version of the csv/excel download file for prioritized CBGs. This data set may eventually be displayed on the map for selected census block groups.

The system needs to classify this data set as a "Socioeconomic factors" indicator. A future version of the cumulative impact score will need this classification as part of the formula.

Both the raw value and the value converted to percentiles for the entire country must be available in the tool.

This data is not stored at the census block group level - it's at the census tract level. There is a separate card representing the work it will take to develop the methodology for combining data from census tracts into census block groups. 

**Tasks**
- [ ]  Obtain DOE LEAD data files
- [ ]  Import the data 
- [ ]  Apply tract-level LEAD score to all census block groups contained in that tract 

**Definition of "Done"**
- [ ] LEAD score at the census tract level is applied to census block groups so that it is available to be used as an input into the score
- [ ] LEAD score is classified as a "Socioeconomic factors" indicator
- [ ] LEAD score is normalized into a percentile for the entire country
- [ ] LEAD score is available to be displayed in the map UI
- [ ] LEAD score is available to be downloaded in the CSV

**Comment by switzersc-usds** [comment]
@BethMattern to update this shortly.
