### ISSUE TITLE
Decision: As a developer, I want to understand if geoplatform.gov is the best option for data storage for J40.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#18]
**Description**
Now that we have access, we should investigate the geoplatform.gov feature set and determine if it can host our datasets, layers, services, and/or FE code. 

**Solution**
Create ADR for using Geoplatform based on research from team.

**Describe alternatives you've considered**
* Cloud.gov
* Federalist
* ArcGIS Hub

**Links to user research or other resources**
Research to be included in ADR

**Tasks**
- [ ] Meet with Joel @ Geoplatform to understand what abilities our credentials grant us
- [ ] Discuss with him and document available feature sets
- [ ] Identify opportunities for dataset hosting
- [ ] Identify opportunities for layer hosting
- [ ] Identify opportunities for static site hosting
- [ ] Identify opportunities for mvt/tile service hosting 

**Definition of "Done"**
- [ ] We've compiled an ADR that includes the above sections and compares the available options

**Comment by mikelmaron** [comment]
Copying over relevant part of my comment from other issue. Working with geoplatform.gov may be a way, as they several options to choose -- from Mapbox, and maybe ESRI, and possibly others. I know for sure is that they have a Mapbox Atlas instance, which is Mapbox's on premise solution that the [National Park Service uses for their public facing maps](https://www.nps.gov/planyourvisit/maps.htm)
