### ISSUE TITLE
As a developer, I want to make sure permissions are locked down to specific IAM roles for AWS operations, so that I can limit harm if these credentials are leaked and lessen reliance on individual team member accounts

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#180]
**Description**
As part of [#101 ](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/101), we had Zivaro alter our permissions to enable us to do various things in AWS (more detail in ticket there). Before wider launch, we should make sure to request IAM roles that are limited in scope to perform only those operations we need so as to limit harm if these credentials are leaked and lessen reliance on individual team member accounts.

**Solution**
Create IAM roles that can only do one thing, set up our pipelines to use these

**Describe alternatives you've considered**
- Our current approach is limited to these specific team members
- A mega-credential that can do anything is not helpful 

**Links to user research or other resources**
N/A

**Tasks**
- [ ] Determine which specific operations we need to perform
- [ ] Request that Zivaro create IAM roles that are scoped to only those operations
- [ ] Setup our CI/CD/Automation/Scripts to use these IAM Roles

**Definition of "Done"**
Our personal accounts are no longer being used to do anything on the geoplatform AWS.

**Comment by esfoobar-usds** [comment]
I did this already.
