### ISSUE TITLE
As a EVCM, I want to zoom in my census block group, so that I can see whether my community is prioritized or on the cusp.

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#182]
**Description**
This user story is about being able to zoom in at zoom level 9 and see for all CBGs in view boundaries and color coding of whether the CBG is prioritized or not

**Solution**
Just zooming in, no search or geolocation.

**Describe alternatives you've considered**
N/A

**Links to user research or other resources**
[Sprint 2 Just Progress list map view
](https://usds.enterprise.slack.com/files/U01E8EWSG5T/F025EKKQWAW/image.png) 
![cbg zoom.jpg](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/fb25724e-a003-4071-be31-26d341667a23)

![Screen Shot 2021-06-22 at 5 13 08 PM](https://user-images.githubusercontent.com/72811320/123000218-4a8c1800-d37d-11eb-9eab-4c1ddbeccdea.png)

Related backend https://github.com/usds/justice40-tool/issues/183 

**Tasks**
  - [ ] Color coding according to mockup set for each CBG in view
  - [ ] There's a legend that explains color coding
  - [ ] Must have zoom in/out buttons
  - [ ] Must have disclaimer about the zoom levels

**Definition of "Done"**
 - We can visit site and see in the most zoomed in view visual representation of CBGs accurately showing those with the highest and on the cusp (according to our tiers) cumulative index.

**Comment by NatHillardUSDS** [comment]
Discussed in dev-design sync earlier today:
* Remove default center dot in block group
* have colorized legend with three colors (for now 3-bucket blue)
* "zoom in" Disclaimer ideally should be present and then disappear as content arises
   * Needs further feasibility assessment to know what we can do 
   * Also subject to further refinement based on outcome of Zooming ticket
