### ISSUE TITLE
As a developer, I need to set the thresholds for CBG scoring (prioritized, cusp, not prioritized), we can easily try out different thresholds.

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#183]
**Description**
For visualization and generally creating lists of prioritized communities we need to be able to easily change the thresholds for prioritized and on the cusp.

Let's do this on the front end for now for user feedback on thresholding, and then move to the backend once it's more firm and needs to be downloadable.

Will make a new ticket for moving this to backend calculation. 

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**
Could do this on the front end, but if we have this in the CSV we'd want to do this in the backend so that we only have the logic in one place. 

**Links to user research or other resources**
Related to front end user story https://github.com/usds/justice40-tool/issues/182

**Tasks**
 - [ ] Investigate where these 0-100% thresholds should be set, starter threshold is 100-75% for prioritized (darkest blue), 74.99%-60% cusp (lighter blue)
 - [ ] Make available for use in map
 - [ ] Make available for use in downloadable CBG list

**Definition of "Done"**

**Comment by switzersc-usds** [comment]
This is currently possible by changing the constants in the map styles.

**Comment by NatHillardUSDS** [comment]
To modify these, change these lines: https://github.com/usds/justice40-tool/blob/main/client/src/data/mapStyle.tsx#L147
