### ISSUE TITLE
New side panel indicator designs for 1.0 release

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1862]
# Purpose

Update the indicator design for the side panel:

![Screen Shot 2022-08-24 at 8 29 52 AM](https://user-images.githubusercontent.com/77702996/186470137-c60db738-5edb-4c85-9d28-ffd7c00755b9.png)

Missing Data icon:
<img width="38" alt="Screen Shot 2022-08-24 at 9 14 09 AM" src="https://user-images.githubusercontent.com/77702996/186469666-49d51892-31bf-438a-9261-f1d7b2a92dd7.png">

Skeleton:
![IndicatorUI - 1 0](https://user-images.githubusercontent.com/86254807/188762621-fc867abf-93cf-437b-88eb-8d038a7e598e.png)

## Tasks
- [x] remove all `up` and `down` 
- [x] replace the `no smoking` _Icon_ with the missing icon
- [x] missing data should use the `error_outline` icon from the USWDS. it should go in the _Icon_ field. 
- [x] instead of highlighting the entire indicator(with a baby blue background), only highlight the _Value_ (dark blue background around the value) when the indicator is above the threshold. change the text color of the value to white.
- [x] instead of a blue dot on the category, change the entire background (to dark blue) of the category when it is above the associated threshold(s), otherwise leave as is. change the text color and the icon color (the plus sign) to white.
- [x] when data is missing, the _SubText_ should say "missing data"
- [x] the value of missing data should be '--'
- [x] _Title_ and _Value_ should have the same font treatment (weight and size)

**Comment by KameronKerger** [comment]
the new side panel design
<img width="162" alt="Screen Shot 2022-08-24 at 9 12 43 AM" src="https://user-images.githubusercontent.com/77702996/186469357-8a9a6ff6-b150-4ce3-8f94-0937d94f455d.png">
missing data should use the error_outline icon from the USWDS
<img width="38" alt="Screen Shot 2022-08-24 at 9 14 09 AM" src="https://user-images.githubusercontent.com/77702996/186469666-49d51892-31bf-438a-9261-f1d7b2a92dd7.png">
it should go in the value field.
the string should say
"missing data"

**Comment by vim-usds** [comment]
@KameronKerger - can you validate the tasks for this ticket? This will also serve as the QA checklist! 

Thanks!

**Comment by KameronKerger** [comment]
ok I edited the above @vim-usds

**Comment by vim-usds** [comment]
@KameronKerger - this is awesome! Thank you!
