### ISSUE TITLE
As a developer, I want a way to write tests for maps so that my code is tested before deploy. 

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#195]
**Description**
We need a way to write tests for maps so that we know our map features are working as expected with every deploy. This isn't something our team has a bunch of experience with, so we'd love some input from the community sharing map testing best practice and tips and tricks. 

**Solution**
TBD

**Describe alternatives you've considered**
TBD

**Links to user research or other resources**

**Tasks**
- [ ] Discuss with open source community
- [ ] Research options
- [ ] Add any required libraries
- [ ] Write a test!

**Definition of "Done"**
- [ ] We have implemented at least one test for our map on the front end that is part of our CI/CD pipeline

**Comment by mikelmaron** [comment]
For mapbox gl js at least, there is a `testMode` and some examples of how to build tests in [the docs](https://docs.mapbox.com/mapbox-gl-js/api/#writing-automated-tests)

**Comment by switzersc-usds** [comment]
Closing this, as we now have map testing in our Cypress setup. It's not perfect but we will improve as we have more specific tests to write.
