### ISSUE TITLE
Side Panel UI tweaks

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#2057]
## Completed:
- [x] Partially should have blue/white - @vim-usds (1)
- [x] IF DAC is YES, then Adjacent and Adjusted low income row should not be shown (3) ([link](https://screeningtool-staging.geoplatform.gov/1829-f3205c/en/?flags=stage_hash=1822/0db67c611cfde16e6430965edb77d7305a331fd3#9.12/27.1377/-98.2394))
- [x] If ADJ is Yes and the value is below 50% then the text should be blue - @vim-usds (1) `#11.5/31.1888/-87.0608`
- [x] HRS_ET signal is broken check here - `#13.97/41.86279/-87.72051`. @vim-usds and @mattbowen-usds (potentially could be a BE issue and captured [here](https://github.com/usds/justice40-tool/issues/2058))
- [x] Update arrow icon to finger point icon in non-selected side panel. @KameronKerger will attach SVG to this ticket.
- [x] publish new base map @KameronKerger 
- [x] @KameronKerger to check about socio-economic

## Design and Engineering required:
- [x] if it is a DAC ADJ is yes and % is above 50% string is not correct (3) ([link](https://screeningtool-staging.geoplatform.gov/1829-f3205c/en/?%20flags=stage_hash=1822/0db67c611cfde16e6430965edb77d7305a331fd3#10.25/28.9874/-98.5254)) @KameronKerger and @vim-usds (add text in yellow)
- [x] If population is N/A and estimated low income is True, then update tooltip text to inform users "Income is not estimated for tracts with unknown populations." (3) - @vim-usds 
- [x] @KameronKerger to fix the dots for the A N Ps
- [x] Tribal 100% YES case (?) - @KameronKerger and @vim-usds

**Comment by KameronKerger** [comment]
the side panel strings should have "socioeconomic" @vim-usds

**Comment by KameronKerger** [comment]
I'm not sure I can fix the ANPs dots, marking done for now
