### ISSUE TITLE
As a developer, I want to ingest the unemployment data set from ACS, so that it can be tested as an input to the cumulative impact score.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#206]
**Description**
The unemployment data set from ACS needs to be available in the screening tool so that it can be used as an input into the cumulative impact score. 

This data set will eventually be displayed in the map for selected census block groups and exported in the list of communities.

The system needs to classify this data set as a "Socioeconomic factors" indicator. A future version of the cumulative impact score will need this classification as part of the formula.

Both the raw value and the value converted to percentiles for the entire country must be available in the tool.

This data is not stored at the census block group level - it's at the census tract level. There is a separate card representing the work it will take to develop the methodology for combining data from census tracts into census block groups. 

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Unemployment at the census tract level is available to be used as an input into the score
- [ ] Unemployment is classified as a "Socioeconomic factors" indicator
- [ ] Unemployment is normalized into a percentile for the entire country
- [ ] Unemployment is available to be displayed in the map UI
- [ ] Unemployment is available to be downloaded in the CSV
