### ISSUE TITLE
As a developer, I want to make the info site and map available at the .gov domain, so that users of the site have a clear URL to use to access the site.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#207]
**Description**
Awaiting a decision on domain name to use. Once that is decided we will submit a request. 
This story is blocked until this is worked out.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Make sure all references on the site to the Name are correct
- [ ] Make ticket for Zivaro to set up CNAME and SSL Cert

**Definition of "Done"**
- [ ] Users can go to the .gov URL and see the site/interact with the map

**Comment by switzersc-usds** [comment]
Subdomain URL in progress. Still waiting on top level domain.

**Comment by switzersc-usds** [comment]
Tasks:

-[] Set up SSL
-[] Update frontend to not use directory path for production environment (this is changing the env config settings)
