### ISSUE TITLE
Improve zoom level performance by bucketing indicator values

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#209]
**Description**
In [#196](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/196) , Mikel left a comment about data preprocessing that they do in the justice-map to improve zoom level performance. 

His description from that ticket:
For the data preprocessing, the approach I took was to assign each block group's indicator value into 10 buckets, then dissolve neighbors by buckets. The result has significantly fewer features, that have no problem rendering at low zoom. The GeoJSON output is then processed into tiles. See [this notebook](https://github.com/earthrise-media/justice-map/blob/main/notebooks/bucket_d_pm25_2.ipynb) for details.

We should adopt similar changes to our own data processing. 

**Tasks**
- [ ] Adopt bucketing for local processing
- [ ] Work with Geoplatform to incorporate this into their processing pipeline
- [ ] Discuss impact of this bucketing on perceptions of accuracy 
- [ ] Frontend performance improves in a measurable way

**Definition of Done**
Feature tiles have all been preprocessed to simplify geometry

**Unknowns**
Does bucketing misrepresent data by aggregating over too-large of an area?

**Comment by NatHillardUSDS** [comment]
As discussed on Friday:
* The outcome of this ticket will be a notebook/script for doing this locally, as well as a tileset posted to AWS with zoom levels 0-5. 
* We will create a separate ticket to handle incorporating these scripts into our pipeline The Right Way

**Comment by NatHillardUSDS** [comment]
Tiles have been posted here:
https://d2zjid6n5ja2pt.cloudfront.net/tiles_low/{z}/{x}/{y}.pbf

Adding a notebook to our codebase also , PR here:
https://github.com/usds/justice40-tool/pull/333

**Comment by NatHillardUSDS** [comment]
Ran a few other experiments also:
1. Simple tract-based mean: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/3cd6e0/en/cejst/?flags=tiles_low=usa_tract#6.94/34.113/-80.522

2. Tract bucketing with mean + 10 buckets: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/3cd6e0/en/cejst/?flags=tiles_low=usa_low#6.94/34.113/-80.522

3. median with 10 buckets: 
 https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/3cd6e0/en/cejst/?flags=tiles_low=usa_low_median#6.94/34.113/-80.522

(for any of these, you can also add &high_tiles=0714_high to get the PR + DC data)

**Comment by janelien** [comment]
Looks good!
