### ISSUE TITLE
[SPIKE] As an EVCM, I want to make sure cumulative index scores for US territories are shown on the map / in the data

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#215]
**Description**
Spike to ensure the map and indicator data can be visualized for the following five US territories that are part of the US Census

* Puerto Rico -- Priority for launch because we know there should be data here. Other territories will likely lack much of the data we need. 
* American Samoa
* Commonwealth of the Northern Mariana Islands
* Guam
* U.S. Virgin Islands

**Solution**
Investigate how territories are represented in the datasets we're using and how we need to update our ETL and tile generation to include territory data.

**Describe alternatives you've considered**
TBD

**Links to user research or other resources**

**Tasks**

- [ ] Ensure map tiles can be shown for the five territories listed
- [ ]  Ensure datasets can be visualized for Puerto Rico
- [ ]  Ensure datasets can be visualized for American Samoa
- [ ] Ensure datasets can be visualized for Commonwealth of the Northern Mariana Islands
- [ ] Ensure datasets can be visualized for Guam
- [ ]  Ensure datasets can be visualized for U.S. Virgin Islands
- [ ] Sync with product and design to understand what our policy or decision rule could be if only a subset of the datasets we use to create cumulative indices for the state CBGs is available (and how we represent in the tool)

# Definition of Done
- [ ] Fleshed out github issue for this feature based on the output of discovery

**Comment by katherinedm-usds** [comment]
Description
Spike to ensure the map and indicator data can be visualized for the following five US territories that are part of the US Census
 - Puerto Rico
 - American Samoa 
 - Commonwealth of the Northern Mariana Islands
 - Guam
 - U.S. Virgin Islands


Solution
TBD

Describe alternatives you've considered
TBD

Links to user research or other resources

Tasks
 - [ ] Ensure map tiles can be shown for the five territories listed
 - [ ] Ensure datasets can be visualized for Puerto Rico
 - [ ] Ensure datasets can be visualized for American Samoa 
 - [ ] Ensure datasets can be visualized for Commonwealth of the Northern Mariana Islands
 - [ ] Ensure datasets can be visualized for Guam
 - [ ] Ensure datasets can be visualized for U.S. Virgin Islands
 - [ ] Understand what our policy or decision rule could be if only a subset of the datasets we use to create cumulative indices for the state CBGs is available

 Fleshed out github issue for this feature based on the output of discovery
