### ISSUE TITLE
As a developer, I want to ingest housing costs and transportation costs , so that they can be tested as an input to the cumulative impact score.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#216]
**Description**
We're currently researching the H+T Index data as a possible source for this information. 

Once we select the appropriate source information about that source will be added here.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"****Definition of "Done"**
- [ ] Housing cost and Transportation cost at the census tract level is applied to census block groups so that it is available to be used as an input into the score
- [ ] Housing cost and Transportation cost are classified appropriately based on how they will be incorporated into the score **outstanding decision**
- [ ] Housing cost and Transportation cost are normalized into a percentile for the entire country
- [ ] Housing cost and Transportation cost are available to be displayed in the map UI
- [ ] Housing cost and Transportation cost are available to be downloaded in the CSV
