### ISSUE TITLE
As an EVCM, I want to be able to clearly see and read orienting information (base map, base layer) about the CBG I'm zoomed in to

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#219]

**Comment by katherinedm-usds** [comment]
**Description**
When zoomed in on the map to the CBG level, orienting information such as neighborhood names or streets are very faint, making it hard for the visitor to understand what they're looking at

**Tasks**
 - [ ] Dev review base map and base layer visualization options with Design (Jane)
 - [ ] Agree on a style and implement in the map

**DoD**
 - [ ] CM review and approval

**Comment by katherinedm-usds** [comment]
Lower priority but putting in "Functional map prototype that visualizes cumulative index" milestone for now

**Comment by katherinedm-usds** [comment]
This may be redundant with https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/110
