### ISSUE TITLE
As a developer I need a way to host my code as we develop, so that I can run it from anywhere

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#22]
**Description**
We need to setup interim hosting so we are able to run our code from anywhere

**Solution**
As an initial stab, we should use cloud.gov sandbox for this purpose

**Describe alternatives you've considered**
Running from one of our machines, but this would require it to always be running; aws, but this would require agency approval

**Links to user research or other resources**
N/A

**Tasks**
- [ ] Create hosted `pg_tileserv` tile server
- [ ] Create hosted static FE site

**Definition of "Done"**
- [ ] Code is setup and running on cloud.gov sandbox
