### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results to HUD RECAP, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#234]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare to the HUD RECAP score, that can be found here: https://hudgis-hud.opendata.arcgis.com/datasets/56de4edea8264fe5a344da9811ef5d6e_0/explore

Note: This is not about bringing in RECAP to be included in the J40 score itself; the goal is to collect datasets that we compare our score output to so that we understand how our score compares to existing indices or indicators. 

**Tasks**
- [ ] ETL RECAP score
- [ ] Modify comparison tool script to load RECAP data and compare it against current score
- [ ] Modify comparison tool script to add stats about the comparison with RECAP with the current score to the report generated at the end of the script

**Definition of "Done"**
- [ ] The J40 comparison tool can be run using the most recent version of our score
- [ ] The comparison tool can access the HUD RECAP data
- [ ] A report / data export can be generated that outputs the results of the comparison on a census tract level
