### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results to SVI data, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#236]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare to the SVI data (CDC/ATSDR Social Vulnerability Index), that can be found here: https://www.atsdr.cdc.gov/placeandhealth/svi/index.html

**Tasks**
- [x] ETL SVI score
- [x] Modify comparison tool script to load SVI data and compare it against current score
- [x] Modify comparison tool script to add stats about the comparison with SVI with the current score to the report generated at the end of the script

**Definition of "Done"**
- [ ] The J40 comparison tool can be run using the most recent version of our score
- [ ] The comparison tool can access the SVI data
- [ ] A report / data export can be generated that outputs the results of the comparison on a city

**Comment by saran-ahluwalia** [comment]
Documentation for 2018 can be found here, including which ACS variables are referenced (if applicable): https://www.atsdr.cdc.gov/placeandhealth/svi/documentation/pdf/SVI2018Documentation-H.pdf

**Comment by saran-ahluwalia** [comment]
Each of the columns, below, represents whether or not a given 2018 Census variables is at least in the 90th percentile

Below, one will note an output for -999 input variables set to -999.

**Questions:**

1.  How should we handle the tracts that have all -999 as inputs?
2. Would it make sense to remove these tracts where input cells are set to -999? Or, do we impute -999 with 0 in order to ensure all tracts are captured? The default will be 0 the sum of each theme (this will be clarified in the README)?

If the latter is chosen, we would need to clearly articulate this in the documentation/README and any consumer-facing document would need a "not available" proxy for this index.

<img width="809" alt="Screen Shot 2022-01-04 at 9 13 07 AM" src="https://user-images.githubusercontent.com/94847739/148071810-69330d95-bcf5-4267-bd5b-8231ee593648.png">

**Comment by saran-ahluwalia** [comment]
An addendum to the above,  item (2). This is the representative breakdown - by state - of thee tracts that would be excluded.
<img width="242" alt="Screen Shot 2022-01-04 at 12 26 15 PM" src="https://user-images.githubusercontent.com/94847739/148099179-64694625-a787-41a5-9292-037b85acff03.png">
