### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results for the state of Colorado to Colorado EJScreen data, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#237]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare our Colorado results to the Colorado EJSCreen score, that can be found here: https://data-cdphe.opendata.arcgis.com/datasets/28112b532dd24912aa04c6c080270525/explore

**Tasks**
- [ ] ETL Colorado EJScreen score
- [ ] Modify comparison tool script to load Colorado EJScreen data and compare it against current score
- [ ] Modify comparison tool script to add stats about the comparison with Colorado EJScreen with the current score to the report generated at the end of the script

**Definition of "Done"**
- [ ] The J40 comparison tool can be run using the most recent version of our score
- [ ] The comparison tool can access the Colorado EJScreen data
- [ ] A report / data export can be generated that outputs the results of the comparison on a census block group level

**Comment by saran-ahluwalia** [comment]
@lucasmbrown-usds I was reviewing the issues that @BethMattern had created. This appears to be out of data as this reflects block groups, not tracts.

**Comment by AdamBuchholz** [comment]
Hi - uploading Mapping for Environmental Justice's Colorado and Virginia data here. Note that any column with a "_score" suffix is a raw value, while any variable with a "_rank" suffix is a percentile.

[Data Dictionary(1).xlsx](https://github.com/usds/justice40-tool/files/7909503/Data.Dictionary.1.xlsx)
[mej_colorado_final(1).zip](https://github.com/usds/justice40-tool/files/7909505/mej_colorado_final.1.zip)
[mej_va_7_1.zip](https://github.com/usds/justice40-tool/files/7909507/mej_va_7_1.zip)
