### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results for the state of Virginia to Virginia EJ data, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#238]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare our Virginia results to the Virginia EJ score, that can be found here: https://mappingforej.berkeley.edu/virginia/

**Tasks**
- [ ] ETL Virginia EJ impact score
- [ ] Modify comparison tool script to load Virginia EJ data and compare it against current score
- [ ] Modify comparison tool script to add stats about the comparison with Virginia EJ with the current score to the report generated at the end of the script

**Definition of "Done"**
- [ ] The J40 comparison tool can be run using the most recent version of our score
- [ ] The comparison tool can access the Virginia EJ data
- [ ] A report / data export can be generated that outputs the results of the comparison on a census block group level

**Comment by saran-ahluwalia** [comment]
@BethMattern @lucasmbrown-usds For Virginia, it is not immediately clear what public data sources (or endpoint for hosting persisted datasets) are available through this resource referenced in the issue. I welcome your feedback on this.

**Comment by lucasmbrown-usds** [comment]
Please contact Adam Bucholtz who helped build that map to ask about how to download the list of Virginia communities. I'll DM you his information.
