### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results for the state of Maryland to Maryland EJScreen data, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#239]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare our Maryland results to the Maryland EJSCreen score, that can be found here: https://www.adaptationclearinghouse.org/resources/maryland-environmental-justice-screen-tool-md-ejscreen.html

**Tasks**
- [x] ETL Maryland EJScreen score
- [x] Modify comparison tool script to load Maryland EJScreen data and compare it against current score
- [x] Modify comparison tool script to add stats about the comparison with Maryland EJScreen with the current score to the report generated at the end of the script

**Definition of "Done"**
- [x] The J40 comparison tool can be run using the most recent version of our score
- [x] The comparison tool can access the Maryland EJScreen data
- [x] A report / data export can be generated that outputs the results of the comparison on a census tract level

**Comment by saran-ahluwalia** [comment]
Data is supposed to be found here: https://github.com/gisumd/EJScreen.

**Comment by saran-ahluwalia** [comment]
One thing that I was not able to access was the EJS raw data from the reference link that was stated in the document.

**Comment by lucasmbrown-usds** [comment]
@saran-ahluwalia -- data now available at: 

```
(
            settings.AWS_JUSTICE40_DATASOURCES_URL
            + "/MD_EJScreen.zip"
        )
```

**Comment by saran-ahluwalia** [comment]
Thanks!

**Comment by saran-ahluwalia** [comment]
Regarding the EJScore in the MDEJscreen. This is the distribution of percentile scores in which each score - call it `N` - represents that census tract's respective overall score is higher than `N`% of the tracts in the state.

The aggregate `EJScore`, here, is the product of the empirical average of the two "Pollution Burden" scores and the empirical average of the "Population Characteristics" categories.

<img width="433" alt="Screen Shot 2021-12-16 at 7 48 41 AM" src="https://user-images.githubusercontent.com/94847739/146375104-e74f080e-7c11-4789-bfd9-b09548f3edcd.png">

**Comment by saran-ahluwalia** [comment]
Something to note in this data are 10 records with no census tract. They have no additional information as well across all population characteristics or for pollution burden. 

<img width="797" alt="Screen Shot 2021-12-16 at 8 30 25 AM" src="https://user-images.githubusercontent.com/94847739/146380927-3a791c85-4b19-42ce-a2a8-467aec4294bd.png">

**Comment by lucasmbrown-usds** [comment]
> This is the distribution of percentile scores in which each score. 

See discussion on the pull request, but it appears to me that this is not a percentile. In the future, I'd expect a graph like the one you produced above should make it fairly obvious that a field is not a percentile -- if you graphed an actual percentile, by definition the graph should be approximately flat between 0 and 1. This bell curve distribution is decidedly un-percentile-like.

**Comment by saran-ahluwalia** [comment]
Understood - yeah that distribution should be uniformly distributed.

**Comment by saran-ahluwalia** [comment]
An addendum to the above (and to your point @lucasmbrown-usds: 
![Screen Shot 2021-12-31 at 3 29 41 PM](https://user-images.githubusercontent.com/94847739/147838339-45c1813f-12c4-4d46-83fc-0f43554fd1c1.png)

**Comment by saran-ahluwalia** [comment]
Just for posterity so no one else misinterprets...This is the PPT that was cited in that Github response: https://mde.maryland.gov/programs/Crossmedia/EnvironmentalJustice/Documents/mdejscreen-cejsc-2-25-2021v1.pdf
And that is what threw me off here.....https://www.mdpi.com/1660-4601/16/3/348/htm (page 4)

<img width="979" alt="Screen Shot 2021-12-31 at 2 23 17 PM" src="https://user-images.githubusercontent.com/94847739/147838411-376aea8a-47d5-494b-9039-b73acf8d5765.png">
)

**Comment by saran-ahluwalia** [comment]
> > This is the distribution of percentile scores in which each score.
> 
> See discussion on the pull request, but it appears to me that this is not a percentile. In the future, I'd expect a graph like the one you produced above should make it fairly obvious that a field is not a percentile -- if you graphed an actual percentile, by definition the graph should be approximately flat between 0 and 1. This bell curve distribution is decidedly un-percentile-like.

An addendum to the above and citing this from @lucasmbrown-usds which should be clarified - primarily for posterity and to ensure there is no further confusion in terminology.

The percentile rank of a score in a distribution is the percent of the population that achieved less than the given score, or, more formally, "the percentage of scores in a specified distribution that fall below the point at which a given score lies."

Please aware of the fact that there is another term in statistics that sounds similar but has a different meaning. This other term is "nth percentile." A formal definition of "nth percentile" is "the smallest value in the set with the property that n% of the data values are less than or equal to it."

A statement such as "a score of 600 has a percentile rank of 80" has a different meaning from a statement such as "the 80th percentile is 600."

The first of these two statements says that 80% of the population had scores that were less than 600, while the second statement says that 80 percent of the population had scores of 600 or less. Statements involving _nth percentiles_, which are not employed in this case, are typically used for defining the cutoffs when the scores have been arranged numerically into 100 equal intervals.
