### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results for the state of Michigan to Michigan EJScreen data, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#240]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare our Michigan results to the Michigan EJSCreen score, that can be found here: https://mpca.maps.arcgis.com/apps/webappviewer/index.html?id=9d45793c75644e05bac197525f633f87

**Tasks**
- [x] ETL Michigan EJScreen score
- [x] Modify comparison tool script to load Michigan EJScreen data and compare it against current score
- [x] Modify comparison tool script to add stats about the comparison with Michigan EJScreen with the current score to the report generated at the end of the script

**Definition of "Done"**
- [x] The J40 comparison tool can be run using the most recent version of our score
- [x] The comparison tool can access the Michigan EJScreen data
- [x] A report / data export can be generated that outputs the results of the comparison on a census block group level

**Comment by saran-ahluwalia** [comment]
@lucasmbrown-usds @BethMattern This link points to Minnesota - not Michigan.

**Comment by saran-ahluwalia** [comment]
Thanks Lucas. This table is pretty useful on it's own: 
https://deepblue.lib.umich.edu/bitstream/handle/2027.42/149105/AssessingtheStateofEnvironmentalJusticeinMichigan_344.pdf?sequence=1&isAllowed=y#page=152&zoom=100,96,96
