### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results to COVID death data, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#241]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare to the COVID death, that can be found here: https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-in-the-United-St/kn79-hsxy

The research question in this case is to see if there is a correlation between the J40 index score and COVID deaths.

**Tasks**
- [ ] ETL COVID death data
- [ ] Modify comparison tool script to load COVID death data and compare it against current score
- [ ] Modify comparison tool script to add stats about the comparison with COVID death with the current score to the report generated at the end of the script

**Definition of "Done"**
- [ ] The J40 comparison tool can be run using the most recent version of our score
- [ ] The comparison tool can access the COVID death data
- [ ] A report / data export can be generated that outputs the results of the comparison on a county level

**Comment by saran-ahluwalia** [comment]
@lucasmbrown-usds @BethMattern 

Here is a sample of data:

<img width="795" alt="Screen Shot 2021-12-13 at 7 19 28 PM" src="https://user-images.githubusercontent.com/94847739/145909864-2b3d6188-efc6-4abf-a609-d9133fd85476.png">

What metric are we capturing here? For example, the proportion of deaths attributed to covid? Or death rate (referencing the week of the record)? Or the relative change in rates.

Also what about vaccination sites and other determinants of access to healthcare? Is the outcome what we should be focused on?

**Comment by lucasmbrown-usds** [comment]
I think it makes the most sense to look at percent deaths from COVID all time. Unfortunately I think this data is only available down to the county level which makes this comparison hard.

**Comment by saran-ahluwalia** [comment]
Understood. I can look into vaccination availability and child infection rates and see if there are associations between asthma and other pulmonary conditions with co-morbidities associated with COVID (or outcomes from COVID 19). I will look for tract -level datasets.

**Comment by saran-ahluwalia** [comment]
We were not able to find this data at the tract level.
