### ISSUE TITLE
As a contributor to J40, I want to compare the J40 score results to areas of the country in the top 25, so that I can understand how the J40 score compares.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#243]
**Description**
The J40 team is working to develop the best possible score for identifying the most underserved and overburdened communities. In order to assess the quality of the score and build credibility in the EJ community, the J40 team build a tool to compare the output of the most recent version of the J40 score with other data sources that generate scores.

We need help adding more data sources for comparison to our tool. We would like to compare to the COVID death, that can be found here: https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-in-the-United-St/kn79-hsxy

The research question in this case is to see if there is a correlation between the J40 index score and COVID deaths.

**Tasks**
- [ ] ETL COVID death data
- [ ] Modify comparison tool script to load COVID death data and compare it against current score
- [ ] Modify comparison tool script to add stats about the comparison with COVID death with the current score to the report generated at the end of the script

**Definition of "Done"**
- [ ] The J40 comparison tool can be run using the most recent version of our score
- [ ] The comparison tool can access the COVID death data
- [ ] A report / data export can be generated that outputs the results of the comparison on a county level
