### ISSUE TITLE
As an EVCM, I want to view a map that visually makes boundaries and prioritized status clear, in an uncrowded and accessible way, so that I can quickly see information in a way that is familiar to me

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#248]
**Description**
We should make sure our visual presentation of data on the map, from the basemap to our feature layer styling, makes it clear what communities are prioritized, in a way that is uncluttered, accessible, and useful to people looking to find their own location on the map.

**Solution**
Let's pick a basemap and tweak feature styling (including feature coloration) to make it clear what block groups have been prioritized. 

**Describe alternatives you've considered**
* Experimented with various styles [here](https://leaflet-extras.github.io/leaflet-providers/preview/)
* https://wiki.openstreetmap.org/wiki/Tile_servers
* Note that we are putting topographic map off the table for July

**Links to user research or other resources**
* Info about map clients generally: https://github.com/usds/environmental-justice/blob/main/engineering/mapping/Introduction.md#client
* Intro to mapbox styles here: https://docs.mapbox.com/studio-manual/reference/styles/
* Info about color contrast: https://designsystem.digital.gov/design-tokens/color/overview/

**Tasks**
- [ ] Choose visually clear basemap that is free/open source, has sufficient detail, and works well with coloration
- [ ] Choose color palette that makes prioritized communities clear against the basemap backdrop
- [ ] Add border at a higher zoom level
- [ ] Tweak alpha at higher zoom levels to prioritize feature display
- [ ] Run accessibility audit of some sort to ensure contrast ratio is appropriate

**Definition of "Done"**
- [ ] Dev and Design have chosen a basemap and feature layer styling that makes it clear what regions are prioritized 
- [ ] The combination of feature styling and basemap have been shown to satisfy accessibility color contrast requirements.

**Comment by switzersc-usds** [comment]
@vim-usds This is likely a great first card for you.

**Comment by switzersc-usds** [comment]
Just a note that we may need help from the open source community on accessibility and mapping.

**Comment by switzersc-usds** [comment]
Adding a Help Wanted label here to solicit input from the community on best practices for picking a color scheme that has accessible contrasting. We need to consider the basemap as well as different densities for the score data, plus scenarios such as when the data is overlaid on a forest or body of water. 

Also interested in input on connotations of colors in different cultures, especially when used in an environmental justice context. For example, we've heard advice not to use red because it has a negative connotation.

**Comment by mikelmaron** [comment]
Some notes from this blog post might help https://blog.mapbox.com/7-best-practices-for-mapping-a-pandemic-9f203576a132

> Color palettes should be colorblind-friendly: All users should be able to understand and learn from your map.
There are aesthetically pleasing, colorblind-friendly color palettes available. [Color guides like this](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) can help full-vision designers envision how color palettes will look to colorblind users. Tools like [Color Oracle](https://colororacle.org/) take this a step further by simulating various types of colorblindness on your screen.

![image](https://user-images.githubusercontent.com/22896/125066332-e063ba80-e080-11eb-94bb-bd1cd322f9f2.png)

**Comment by katherinedm-usds** [comment]
It sounds like amongst the available base maps, Nat and Jane had reviewed together and Jane advised what's currently used is the best one for launch. Seems like Design input is no longer needed for this ticket
