### ISSUE TITLE
As an EVCM, I want to see clearly at the top of the site the key things I can navigate to (About, Explore the tool, Data & Methodology, Contact in header)

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#249]
**Description**
Header should be updated with the links to the pages within the site that we know we'll support for July 27th. 

**Solution**
Implement links to About, Explore the tool, Data & Methodology, Contact in the header

Tom will also add a few extra things here: accessibility support and page meta tags. Probably will also implement localization (breaking out the strings and putting into localization strings).

**Describe alternatives you've considered**

**Links to user research or other resources**
Related to https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/233 and https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/113

**Tasks**
 - [ ] Update header links, remove "Timeline" and "CEJST"
 - [ ] Link Methodology to new Methodology page https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/233
 - [ ] Link Contact to new Contact page https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/113
 - [ ] Update logo

Already done (at least until content is finalized) is "About" which links to the informational page.

**Definition of "Done"**
 - [ ] Links are navigable on http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/f12ab4/en/ or similar dev/demo URL

**Comment by switzersc-usds** [comment]
Keep Timeline page around, just don't use it yet. We may want this back later.

**Comment by katherinedm-usds** [comment]
Moving to Design column because where we've landed after usability testing is that instead of "Methodology", the header should show "Data & Methodology".

**Comment by janelien** [comment]
updated design

![header.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/de6aaaa2-945e-4b4a-9069-d964579a613d)

**Comment by janelien** [comment]
updated with graphic

![header.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/3725acfd-67b2-4081-af67-c9ad82edf914)

**Comment by janelien** [comment]
![shape_thing_1@2x.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/d3132e59-f959-46bf-bf6d-d3458319f893)

**Comment by switzersc-usds** [comment]
Nice logo!

**Comment by switzersc-usds** [comment]
@janelien to add mobile too

**Comment by janelien** [comment]
mobile header 

![mobile header.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/9ce3d62b-18c0-4878-912d-d980ade5d956)
