### ISSUE TITLE
As a developer, I want to have a YAML file describing the metadata for our existing datasets.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#262]
**Description**
We will be using the YAML file to be the source of truth for datasets used in the tool, and the frontend (for now) will be calling on the YAML files to display information on the website. We need to create these YAML files and flesh it out with info for our existing data sets.

**Solution**
Create one YAML file per dataset and update with necessary fields. During the data-pipeline process we also want to pull these and create a JSON file for the frontend to consume.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Identify the list of fields needed by the mockup (ie what we want on the site) - Sync with Design on what's available and what we might want. These are in screenshots.
- [ ] Identify what other fields we want in the file
- [ ] Session showing product and design how to create and update these files
- [ ] Create files
- [ ] Implement JSON conversion

**Definition of "Done"**
- [ ] We have an accurate YAML file for each of the 3 data sets (ACS, EJScreen, and housing)
- [ ] Data is available from S3 or Github as JSON file (this may be generated and available from a Github action)

**Comment by NatHillardUSDS** [comment]
Note from discussion just now: we should convert to json for easier consumption by the frontend

**Comment by BethMattern** [comment]
Here is a sample .csv of what we were thinking of including. This isn't the final list of indicators but is an example of the data we want to display.
[Just Progress Datasets - Sheet1.csv](https://github.com/usds/justice40-tool/files/6772376/Just.Progress.Datasets.-.Sheet1.csv)

**Comment by BethMattern** [comment]
Here's an excel file for the data indicators that are currently involved in the score that should be the source for this page.[https://app.zenhub.com/files/358242767/1b63fbb7-f7d5-4673-88b0-8515f9846e63/download](https://app.zenhub.com/files/358242767/1b63fbb7-f7d5-4673-88b0-8515f9846e63/download)

**Comment by switzersc-usds** [comment]
@BethMattern can you please list the fields here from the spreadsheet? This should be a list of all fields the frontend needs for a given indicator or dataset.

**Comment by BethMattern** [comment]
Fields needed to display in UI:
Indicator name
Long description
Short description
Data resolution
Category
Data source
Date range
Link to source

cc: @esfoobar-usds @switzersc-usds

**Comment by BethMattern** [comment]
@esfoobar-usds this can be closed right? It's an old version of the YAML work I believe.

**Comment by esfoobar-usds** [comment]
No, this is a bit different -- it's for the datasets, although not sure if @emma-nechamkin has a separate tracking ticket, in which case this one can be closed.

**Comment by esfoobar-usds** [comment]
Oh so it's https://github.com/usds/justice40-tool/issues/1254, so yeah, this can be closed.
