### ISSUE TITLE
As an EVCM, I want the map to be centered on the US at the right lat/long and at the right bounds/extent, so that I am not confused by non-relevant map regions

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#264]
**Description**
We should center on and restrict our map to a relevant region and restrict zoom levels / bounds / extent such that we only highlight the US

**Solution**
Set `center` , `bounds`, and `minZoom` properties appropriately to avoid showing non-US regions to our users

**Describe alternatives you've considered**
* Allowing users to see the whole world, as things are currently set up (see [here](http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/f12ab4/en/) ) means that they can get to places outside of the US, and we heard in user testing that this was confusing

**Tasks**
- [ ] Set final `center` according to US map conventions
- [ ] Set final `minZoom` and `maxZoom` according to US map conventions
- [ ] Set final `extent`/`bounds` to the appropriate values according to US map conventions

** Gotchas ** 
- [ ] Need to account for Alaska
- [ ] Need to account for other US territories

**Definition of "Done"**
Users see only the US and cannot zoom outside of it.

**Comment by NatHillardUSDS** [comment]
This was already done as part of fixes for the latest version of MB
