### ISSUE TITLE
As an EVCM, I want a good experience using the app on mobile and tablet, so that I can consult information without a dedicated desktop machine

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#268]
**Description**
We should do a mobile audit to ensure our designs look good on mobile and tablet devices, as many users may not have access to desktop machines with larger screens.

**Solution**
* Run through app use cases on mobile and tablet devices alongside Design, note any visual issues
* Run through front end code and determine what should change (eg use of pixels)
* Discuss larger changes with Design if necessary

**Describe alternatives you've considered**
* Not having support for mobile is not an option

**Links to user research or other resources**
* According to [analytics.gov](https://analytics.usa.gov/?=dg) the majority of users of government websites are on mobile

**Tasks**
- [ ] Design - create mobile designs for 480px and above, and below 480px, with the caveat to see if there are special cases for certain components required for 320px (i.e. if map needs special consideration for 320px)
- [ ] Perform manual audit on real devices of mobile-readiness against our full website feature set, document any issues on mobile devices, paying special attention to 320px configuration
- [ ] Dev implement mobile designs using updated breakpoint values and audit results (subtask tracked in https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/575)
- [ ] Perform dev audit of front end code and determine what needs to change (should be part of 575)
- [ ] ~~Come up with a plan to address highest priority issues, determine which are for launch~~ (breakpoint configurations have been simplified) 

**Definition of "Done"**
- [ ] We have documented all issues for our site on mobile devices
- [ ] We have dev focused cards on improvements we need to make to front end code

**Comment by katherinedm-usds** [comment]
Jane posted a version of mobile designs but there are still changes proposed from usability testing and technical feasibility changes (i.e. side panel next to map for score) that need to be incorporated into mobile designs. We should make sure mobile designs are ready for Thursday for Sprint 4.

**Comment by janelien** [comment]
See mobile designs under Sprint 4

**Comment by vim-usds** [comment]
Adding requirement

- look into map and sidepanel taking up full width
- also investigate new breakpoint for when the side panel should pop below map

**Comment by switzersc-usds** [comment]
these are th default breakpoints with USWDS:

![image.png](https://images.zenhubusercontent.com/60994445b305970bf293d619/4c76047f-731f-4840-900b-68d6a8206fab)

**Comment by switzersc-usds** [comment]
Convo 8/31:

- We will use USWDS default breakpoints
- We will only support first two breakpoints (480 and 640)
- Katherine is doing an audit today on whether our current site has a decent experience for those two breakpoints
- Katherine will make new discrete bug tickets for each problem identified during the audit and we will triage those as usual for bug tickets (review, prioritize for this or next sprint depending on P1/P2/etc)
- In a future sprint we will do a full mobile audit for all breakpoints. This will result in either more design work showing new designs for different breakpoints and/or new bug tickets to fix breakpoint issues
