### ISSUE TITLE
As a developer, I want to have more layers of census data to work with, so that people can zoom in more

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#274]
**Description**
We currently only have census data at levels 5-11, meaning if people zoom in beyond this, they don't see any data at the moment. We should add and process more. 

**Solution**
We need to add levels beyond 11 to ensure a good zoom experience. 

** Open Questions **
* Should check this with Geoplatform to make sure they're ok with the additional filesize implications of this (see [here](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=-125.59475,23.828006,-66.191429,49.925794))
* Should check with OSS community about what a good max zoom is
* Who should do this? Do we need Xentity to, or can we?

**Describe alternatives you've considered**
- currently zoom level 11 is not sufficient for zooming into dense places like NYC - see https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/a67b35/en/cejst/?flags=mb 

**Links to user research or other resources**
N/A

**Tasks**
- [ ] Agree on max zoom
- [ ] Decide who will do this, us or Geoplatform
- [ ] Process tiles up to that greater zoom level
- [ ] Incorporate into our tile-building pipeline going forward 
- [ ] Set the maxZoom level for maps and layers to allow users to zoom in

**Definition of "Done"**
- [ ] Users can zoom in to some level beyond 11

**Comment by switzersc-usds** [comment]
Geoplatform contacted 7/6; we also have a meeting with them on 7/7 and should have an identified path forward by then.

**Comment by switzersc-usds** [comment]
@NatHillardUSDS Do we need design support or a conversation about this, e.g. on good max zoom?

**Comment by NatHillardUSDS** [comment]
with "overzoom", we can get more scaling for free, and in theory shouldn't need to set a max beyond the default. in practice there may be corruption of individual features ; once we fix the overzoom issue we can reassses

**Comment by NatHillardUSDS** [comment]
Part of this will be fixed with [#311](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/311) -- if we can fix the tiles disappearing, its likely this will be sufficient; that said, we may need to still request more info beyond this

**Comment by katherinedm-usds** [comment]
@NatHillardUSDS is this issue still blocked?

**Comment by janelien** [comment]
Regarding max zoom, I think zoom level 16 is sufficient in order to see the smaller streets people will use to identify their community. From what I understand, we get up to zoom level 22 for "free" so that's good.

**Comment by NatHillardUSDS** [comment]
After the fix for [#311](https://app.zenhub.com/workspace/o/usds/justice40-tool/issues/311), it appears we don't need to ask for more tiles from Geoplatform, and can rely on "overzoom" to scale up our tiles from zoom level 11 to any zoom above this. 

That said, given the way that fix works, when you're looking at zoom level 16, you're actually looking at the same tiles from zoom level 11, but scaled up. This scaling can result in distortion, at least in theory. (in practice, because these are vector tiles and thus defined by mathematical formulae instead of images, the effect of this scaling is typically a lot smaller than it would be for, say, early 2000s image-based internet memes).

I think the next step here is to move this ticket to review, and Jane, for you to take a look at the branch here: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/be0256/en/cejst/ , to determine whether the experience is acceptable at higher zoom levels with our current setup. If it is, we can close this out!

**Comment by janelien** [comment]
@NatHillardUSDS - I think this looks good. It's a little odd that as one zooms in from around zoom level 17 to 18+ the labels get smaller in font size but I don't think it's a big deal.
