### ISSUE TITLE
As an EVCM, I want to see all states and territories on the initial map load, so that I feel my community is included.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#280]
**Description**
Resulting from #112, we have a path forward for ensuring visual representation for all states and territories on initial map load. 

**Solution**
Add small icons for the identified US territories and states that not visible on the initial map load, and set those icons to link to show that state/territory at a good zoom level. 

We are starting with AK, HI, and PR, because we have data for these on the map so far, and will add other territories after territory data spike. 

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [x] Mockup for this
- [x] Find right icons or way to represent AK, HI, and PR
- [ ] Implement
- [ ] Tests! 

**Definition of "Done"**
- [ ] A user can see icons for these off-map states/territories on the initial page load and click them to get a zoomed in look at that state/territory on the map.

**Comment by katherinedm-usds** [comment]
@janelien incorporated a version of these Hawaii, Alaska, territories type of map navigation shortcuts in the Future Vision designs

![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/9d629f72-22a7-4fca-bd54-b041f5d5d0a8)

**Comment by janelien** [comment]
mockups have been updated

![Screen Shot 2021-07-06 at 11.00.49 AM.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/2db1df10-8390-4ebd-a663-c99d85f260cd)

**Comment by janelien** [comment]
This site is an example of the interaction: https://www1.eere.energy.gov/apps/ed/j40_project_map/j40_review.html
