### ISSUE TITLE
As an EVCM, I want to have only relevant information shown to me in the block group detail view, so that I'm not confused by too much information (Backend only sends relevant info).

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#287]
**Description**
We only want to send data elements to the frontend that the frontend design needs.

**Solution**
Update data-pipeline to generate GeoJSON and tiles that have only data elements we want in the sidebar.  Also data should include property names that are user readable; this could be a column that is distinct from the raw/machine-readable property name.

**Describe alternatives you've considered**
- The current full list of properties (almost 100) feels overwhelming

**Tasks**
- [x] Work with Product to define the relevant list of properties to include (and exclude) 
- [ ] Work with design to devise a good column label and formatting of data within that column 
- [ ] Create a filter on our CBG detail view that only shows these properties

**Definition of "Done"**
- [ ] The CBG detail view only shows the chosen properties

**Comment by NatHillardUSDS** [comment]
(Passing off to Vim per convo just now!)

**Comment by janelien** [comment]
Worked with Beth on content

![side panel.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/e606b86d-7557-4f61-89d0-ac907755f76a)

**Comment by janelien** [comment]
side panel if no census block group has been selected

![side panel_no selection.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/097de6c3-8072-4d76-8834-7ff7f3de8f6b)

**Comment by KameronKerger** [comment]
can we work on the content for that blank slate a bit more? I'm worried because it will be people's first interaction with the map. we can try to explain what a census block group is and what the indicators are? this might be a good place to pull in some of the content. we could also maybe pull the zoom warning in and give people some instruction into how to zoom and how to know if the data is "calculating" or if you just need to wait.

Suggested text changes:

The data indicators used by the tool are shown when the map is zoomed-in and a Census block group is selected. (This can either be a tool-tip or content) A Census block group is a generally between 600 to 3,000 people. It is the smallest geographical unit for which the bureau publishes sample data, i.e. data which is only collected from a fraction of all households. 

The initial datasets used by the screening tool are:

Poverty (less than 200% of federal poverty line)
Less than high school education
Linguistic isolation (primarily speaks languages other than English)
Unemployment
Housing-burdened low income

Zoom with the controls provided (can put the graphic) or with your trackpad or mouse.

After each zoom, give the map a moment to load before you zoom further. (ideally we have a wait graphic that is used in the UI and shown here as well - need to understand more about zoom performance first though)

**Comment by janelien** [comment]
@KameronKerger - Yeah, I like that idea of using the space for some info. I might recommend less text but I'll pull in some of the suggested text you wrote.

**Comment by janelien** [comment]
updated no selection side panel

![side panel_no selection.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/f2f3db7f-58fc-4912-90c2-552df6185203)

**Comment by janelien** [comment]
I was informed there's an update. Instead of "Value" it is back to "Percentile (0-100)"

![side panel.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/691d29c4-4411-44bb-9568-9dd918f87e75)

**Comment by KameronKerger** [comment]
since the most important information on this panel is the status and the cumulative score can we emphasize that information visually to create a hierarchy? even drawing from the Tree Equity people where they contain that information in a visual element. right now it is reading as the same and visually flat to me and users will want to know what is important and what is supporting information...

**Comment by switzersc-usds** [comment]
For this, just focus on getting the properties we need in the data that the front end uses. Do not work on adding the short description  that you see in the sidebar screenshots; I will make a separate ticket for figuring that out.

**Comment by vim-usds** [comment]
Hello @NatHillardUSDS and/or @esfoobar-usds,

For version 1 are we going with GraphQL to get this data or maybe just start with a direct call to an API? If we are starting with the latter, maybe this could be a starting point for the data contract?

```
{
    "data": {
        "censusBlockGroup": 8013013308, //int
        "countyState": "Washington County, Disctrict of Columbia", // string
        "population": "59,002", //string
        "categorization": "Prioritized", // string
        "cumulativeIndexScore": 98.8 //float
    },
    "indicators": {
        "poverty": 98.8, //float
        "education": 98.9, //float
        "linguisticIsolation": 99.0, //float
        "unemployment": 97.2, //float
        "housingBurden": 98.4 //float
    }
}
```

**Comment by vim-usds** [comment]
Meant to wrap the indicators in the data, haven't figured out how to update tickets yet!

{
    "data": {
        "censusBlockGroup": 8013013308, //int
        "countyState": "Washington County, Disctrict of Columbia", // string
        "population": "59,002", //string
        "categorization": "Prioritized", // string
        "cumulativeIndexScore": 98.8, //float
        "indicators": {
            "poverty": 98.8, //float
            "education": 98.9, //float
            "linguisticIsolation": 99.0, //float
            "unemployment": 97.2, //float
            "housingBurden": 98.4 //float
        }
    }
}

**Comment by esfoobar-usds** [comment]
@vim-usds we won't be doing GrpahQL for this piece. This is information baked into the tiles themselves.

**Comment by esfoobar-usds** [comment]
@vim-usds after this ticket is done, we should talk about removing the client-side truncation of the data fields.

**Comment by vim-usds** [comment]
@esfoobar-usds totally agreed. The front-end version of this was just merged. Please feel free to ping me when its done and we can discuss what changes are needed in the frontend to take this ticket's effort into account.
