### ISSUE TITLE
As an EVCM, I want to easily access CBG detail information on both desktop and mobile, so that I don't have to scroll forever. (Implement sidebar)

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#288]
**Description**
Our current popup-based CBG detail view takes up a lot of screen space, especially on mobile. We should consider moving to a sidebar-based map as seen in sites like [Tree Equity Score](https://treeequityscore.org/map/#10.5/33.6607/-112.1231)

**Solution**
We should move the content that is currently in a popup to a sidebar instead, and move that sidebar to below the map on mobile

Support: Desktop chrome, firefox, safari, and edge; Mobile chrome and safari. Assume 400px breakpoint.

If one of the above browser reqs becomes a blocker, let's discuss at the time. 

**Describe alternatives you've considered**
- The current popup is large and intrusive, and doesn't look good on mobile

**Links to user research or other resources**
- NEEDED: Design spec

**Tasks**
- [x] Work with design on a spec to show this information
- [ ] Be sure to show county!
- [x] Move popup content into the sidebar instead
- [x] Ensure sidebar is moved below the map on mobile

**Definition of "Done"**
- [x] CBG detail content is visible in a sidebar on desktop
- [x] CBG detail content is visible below the map on mobile

**Comment by switzersc-usds** [comment]
@NatHillardUSDS  Is this a duplicate of #268?

**Comment by NatHillardUSDS** [comment]
#268 is more of a general mobile audit - this is probably more properly a subtask, related specifically to the popup. 

Here's a screenshot from the current mobile experience to be clearer about what this is referencing:
![IMG_2612](https://user-images.githubusercontent.com/72811320/124617123-af974180-de44-11eb-96e9-6a087036ce0c.PNG)

![IMG_2611](https://user-images.githubusercontent.com/72811320/124617120-aefeab00-de44-11eb-8721-74bf2612d94e.PNG)

**Comment by janelien** [comment]
See mobile designs under Sprint 4

**Comment by vim-usds** [comment]
Status
- ~Basic permanent side panel container renders (HTML/CSS)~
- retain state and update after transition ends
- filter data on client side
- Style component(s)
- unit tests
- e2e tests
- update with actual server data

**Comment by vim-usds** [comment]
Let's decide which ones we want to do in this ticket vs a new ticket:

- [ ] BUG: click on feature on mobile via dev console (priority)
--  try separate instance of ReactGL component
--  try to use media query instead of changing height in ReactGL component
- [ ] WARNING: map warning (priority? )
- [ ] PROCESS: test cypress test on GH (priority)
- [ ] STYLING: factor out string literals 
- [ ] unit test not rendering
- [ ] JS doc es-lint thing
- [ ] rem vs px 
- [ ] cypress forEach()

**Comment by vim-usds** [comment]
Hi @janelien 

here's the URL to test this!

http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/5ff1e7/en/

Please let me know if you have any feedback!

Thanks!

**Comment by vim-usds** [comment]
Status

- PR feedback has been integrated.
- Cross browser testing has not been done. Minimal mobile testing is in place.

**Comment by janelien** [comment]
Met with @vim-usds and discussed a few small edits.

Changing from title case to sentence case (for Housing burden and Linguistic isolation)
Unemployment to be 'Unemployment rate'
Changing mobile breakpoint to 414px. It's currently at 400px, but 400px doesn't work for iPhone 11s. This would be a temporary fix with a more permanent fix being tackled in the mobile readiness ticket.
We looked at breakpoints and 800px would be good for pretty much all tablets/mobile devices. Tablet view would benefit from being the same as the mobile view.

Overall, it's looking great!

**Comment by janelien** [comment]
A bit more of what we looked at for reference:

https://www.browserstack.com/guide/ideal-screen-sizes-for-responsive-design

According to the Worldwide Screen Resolution Stats (Jan 2020 – Jan 2021), the most commonly used resolutions across mobile, desktop, and tablet are:

1920×1080 (8.89%)
1366×768 (8.44%)
360×640 (7.28%)
414×896 (4.58%)
1536×864 (3.88%)
375×667 (3.75%)

and this: https://www.icwebdesign.co.uk/common-viewport-sizes

**Comment by vim-usds** [comment]
@janelien 

Thanks for the feedback. Ended up just pushing the version where we have a breakpoint at 400. 

I think we have a ticket for mobile compatibility what we can re-visit the breakpoints and may want to add another few breakpoint to get the iPhone
