### ISSUE TITLE
As a data developer, I want to limit the size of the mbtiles database, so that the frontend can have a performant experience

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#302]
**Description**
There are a few optimizations that have been suggested for the mbtiles database from geoplatform to improve performance. We should adopt these. 

**Solution**
- Let's do the following optimizations to shrink tile sizes.

**Describe alternatives you've considered**
- By default, map loading is slow with the full set of 95+ properties

**Links to user research or other resources**
- From [this link](https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/):  
```render time = constant time + [ number of sources * per source time ] + [ number of layers * per layer time ] + [ number of vertices * per vertex time ]```
Thus if we can shrink the number of properties per tile we can overall lower load times.

**Tasks**
- [ ] Limit the mbtiles db properties to the values shown on the spreadsheet for the popup
- [ ] Limit floating point values to two significant figures (maybe using strings? we can convert types on the frontend)
- [ ] Make “official” property names shorter (we'll need an official long name to show in the UI)

**Definition of "Done"**
The mbtiles database has the above modifications in place

**Comment by NatHillardUSDS** [comment]
We've discussed a bit the possibility of having multiple tilesets with different information, having one that only has the score, for instance, and another for other details, which is queried when you click "more" in the detail view, for instance. This may not be necessary if there is only a small number of properties that we need to care about in the popup (it sounds like this may be the case)

**Comment by esfoobar-usds** [comment]
@NatHillardUSDS what are the columns that will be shown in the popup? Is there a document where I can check?

**Comment by esfoobar-usds** [comment]
@NatHillardUSDS FYI, I created a list of the columns we want baked into the tiles [here](https://github.com/usds/justice40-tool/blob/7b37f50b2ae4dd4c22589acbd2387d449a252f57/score/etl/score/etl_score_post.py#L26-L33)
