### ISSUE TITLE
As a J40 developer, I want to be able to generate a zip file that represents the score and upload it to a static S3 URL, so that EVCMs can download it

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#303]
**Description**
We need to add a step to the ETL Score generation, so that it generates a downloadable version of all the CBGs with their indicators and scores in a static S3 URL that the frontend client can point to for EVCMs to download it locally on their computer.

**Solution**
Add a method on the Score ETL that generates a CSV locally and if there are AWS credentials present on the container, uploads it to an S3 bucket.

**Describe alternatives you've considered**
None

**Links to user research or other resources**

**Tasks**
- [ ] Design/product to provide column names
- [ ] Create the local file with the CSV columns based on a spec 
- [ ] Write functionality to upload the file to S3

**Definition of "Done"**
- [ ] A CSV file is generated on every score run

**Comment by katherinedm-usds** [comment]
Adding Glennette as design assignee so that dev working on this knows design point of contact

**Comment by katherinedm-usds** [comment]
Glennette to provide mockup or list of column names for .csv

**Comment by glennettec** [comment]
After I finished styling the excel file, I tried to export and save as a .csv file. I found that .csv files are limited to one tab and can't hold information about the datasets in a separate tab like excel. No styling needed.

 [Screening Tool Datasets.csv](https://app.zenhub.com/files/358242767/14037671-6cf2-44d6-8487-9f6736adbbc6/download)

**Comment by glennettec** [comment]
Added "Population" as a column.

[Screening Tool Datasets csv download.csv](https://app.zenhub.com/files/358242767/95d6502b-90ba-4ddd-a658-1807110834a9/download)

**Comment by switzersc-usds** [comment]
This could post directly to the Github repo instead of S3.

**Comment by glennettec** [comment]
Updated .csv file. No need for styling.

[Screening Tool Datasets .csv](https://app.zenhub.com/files/358242767/3460f595-dc9f-4a5d-acaa-3581bbf57872/download)

**Comment by KameronKerger** [comment]
[Prioritized_Communities_List.pdf](https://github.com/usds/justice40-tool/files/6903480/Prioritized_Communities_List.pdf)

**Comment by esfoobar-usds** [comment]
Per @glennettec:

Updated mockup for the .xls file. Passed Excel's accessibility checker.

Four tabs:

- About the score
- Dataset definitions
- Score data
- Non-score data

[Screening Tool Datasets download](https://app.zenhub.com/files/358242767/b44d9a55-db3e-4144-962e-4aa393d7b472/download)

**Comment by esfoobar-usds** [comment]
At Sprint Planning we discussed making the Excel file simpler. We will need to create a separate ticket with the contents of this new version of the Excel file. @glennettec to coordinate with engineering.

For this ticket we will just the CSV.
