### ISSUE TITLE
As a Python developer, I want the linter to check that every function has docstrings, so that I can read the codebase

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#308]
**Description**
Implement a linter to check that all functions and methods in our backend Python code have docstrings. 

This will help make the codebase more readable and updateable in the future. 

**Describe alternatives you've considered**
Without a docstring linter, we could just use the peer review process to enforce having docstrings for everything.

**Tasks**
- [ ] Choose a docstring linter
- [ ] Implement it 
- [ ] Fix functions/methods without docstrings 
- [ ] Add linter to pre-commit or other steps

**Definition of "Done"**
* A developer cannot merge code with functions/methods that do not have docstrings.

**Comment by widal001** [comment]
@switzersc-usds @ginabeena @NatHillardUSDS Thanks for your patience while I got a chance to extract this unique list of errors from the `pylint` and `flake8` linters. Here's a breakdown of those errors:

### Pylint

- [C0103: invalid-name](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0103.html)
- [C0115: missing-class-docstring](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0115.html)
- [C0116: missing-function-docstring](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0116.html)
- [C0206: consider-using-dict-items](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0206.html)
- [C0301: line-too-long](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0301.html)
- [C0411: wrong-import-order](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0411.html)
- [C0412: ungrouped-imports](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0412.html)
- [R0205: useless-object-inheritance](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/R0205.html)
- [R0902: too-many-instance-attributes](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/R0902.html)
- [R0914: too-many-locals](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/R0914.html)
- [R1720: no-else-raise](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/R1720.html)
- [R1732: consider-using-with](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/R1732.html)
- [W0107: unnecessary-pass](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W0107.html)
- [W0221: arguments-differ](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W0221.html)
- [W0511: fixme](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W0511.html)
- [W0611: unused-import](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W0611.html)
- [W0612: unused-variable](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W0612.html)
- [W1203: logging-fstring-interpolation](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W1203.html)
- [W1309: f-string-without-interpolation](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/W1309.html)

## Flake8

- E501 line too long
- F541 f-string is missing placeholders
- F841 local variable 'min_max_fields' is assigned to but never used

**Comment by widal001** [comment]
Some of the links to the specific error messages are breaking above, so here's the page with all of the errors for `pylint` https://vald-phoenix.github.io/pylint-errors/#list-of-errors

**Comment by widal001** [comment]
I updated the list above with the errors I was able to fix directly. The remaining errors are listed below:

```toml
disable = [
    # Errors that I would recommend disabling permanently
    "C0114",  # Disables module docstrings
    "R0201",  # Disables method could have been a function
    "R0903",  # Disables too few public methods
    "C0103",  # Disables name case styling
    "W0511",  # Disables FIXME warning
    "W1203",  # Disables f-string interpolation for logging warning
   
    # Errors temporarily ignored for further discussion
    "W0107",  # Disables unnecessary pass
    "W0221",  # Disables arguments differ
    "R0902",  # Disables too many instance attributes
    "R0914",  # Disables too many local variables
    "W0621",  # Disables redefined outer name
    "C0302",  # Disables too many lines in module
    "R1732",  # Disables consider using "with"
    "R1720",  # Disables unnecessary "else" after "raise"
    "C0206",  # Disables consider iteratig with ".items()"
    "C0200",  # Disables consider using "enumerate" instead of "range" + "len"
    "W0612",  # Disables unused variable
    "W0613",  # Disables unused argument
    "C0116",  # Disables missing function or method docstring
    "C0115",  # Disables missing class docstring
]
```
