### ISSUE TITLE
As a developer on the project, I want to understand and easily update our system architecture, so that I can contribute at a high level to the project

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#32]
**Description**
We should document our current thinking about project architecture for future reference, in a way that can be updated and evolved over time with community support

**Solution**
Utilize mermaid.js to setup a pipeline allowing us to create text-based diagrams and render them as images

**Describe alternatives you've considered**
* Pure image-based diagrams get out of date and are difficult to version
* Mural requires an account and does not support versioning

**Links to user research or other resources**
[Mermaid](https://mermaid-js.github.io/) - Mermaid is an excellent text-based tool for creating diagrams

**Tasks**
- [ ] Document current architecture in Markdown-based Mermaid file
- [ ] Create github actions steps to automate the creation of similar diagrams in the future
- [ ] Document the workflow for future reference in the README
**Definition of "Done"**
