### ISSUE TITLE
As a developer, I understand what device/OS/browser configurations are most important, so that I can plan test automation accordingly.

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#329]
**Description**
We discussed at discussion half hour today bug process and holistic QA process defining a Prod/Design defined prioritized list of devices/OS/browsers. 

**Solution**
Outcome was for product to give devs a prioritized list of devices/OS/browsers for use in standing up test automation, in conjunction with prioritized list of workflows/units of functionality.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Product + Design review browser configs on https://analytics.usa.gov/ including analytics for specific sites (i.e. DOE's site) 
- [ ] Product + Design provide list and prioritization of devices/OS/browser configs we'd want coverage for

**Definition of "Done"**
- [ ] list provided to dev to guide their prioritization of automation

**Comment by glennettec** [comment]
I ran two reports on Google Analytics based on usage of the DOE and EPA web sites for the top 25 devises, browsers, and OS.

[EPA agency profile](https://app.zenhub.com/files/358242767/7c5a8db2-f4df-4f50-9774-93e527850dd5/download)

[DOE agency profile](https://app.zenhub.com/files/358242767/a9290a1b-bc14-4ffb-90bd-e2e9cc8692f9/download)

**Comment by katherinedm-usds** [comment]
@glennettec thanks for the GA reports! based on those + any configs on SortSite that are flagged, please make a recommendation for must-test or nice-to-test OS/browser configurations and advise if some are higher priority than others

**Comment by glennettec** [comment]
![image.png](https://images.zenhubusercontent.com/60e71e455052ef541fcc40c3/7544077e-ff5e-42d7-84b4-bd20cc38ba9b)

**Comment by switzersc-usds** [comment]
Still need: 
- [ ] Versions of the device/OS/browsers also if possible
- [ ] Convo and decision about what we need to support
- [ ] New ticket for adding testing support based on decision

**Comment by glennettec** [comment]
Here are the results from my research for OS/Browser/Browser version based on GA for the DOE and EPA sites.

[Browser Stats](https://app.zenhub.com/files/358242767/7c455fc1-62b4-4c8a-b9fa-dcb97af8b4e2/download)

**Comment by BethMattern** [comment]
There is a new card to track research on breakpoints

**Comment by BethMattern** [comment]
@vim-usds please review the browser stats file and let @glennettec know what else you'd like to see. We can add that to #490.

**Comment by vim-usds** [comment]
@glennettec 

This looks great! You table really summarizes nicely the must have _browsers_ and _OS_:

### Must-have browsers
- Chrome
- Safari

### Must-have OS
- Window
- iOS
- Android

While the category column does specify general devices, it would be great to have more specificity here. Specifically around the exact _width_ and _height_ for our must-have devices. It would be awesome to  have the _device sizes_ (namely _width_ and _height_) added to the list. Below is what that list might look like (numbers have no real research to them):

### Must-have devices sizes
- 768 x 1024
- 320 x 480 (and reverse)
-- specifying and reverse will allow us to take both portrait and landscape mode into consideration.
- 414 x 736
- etc

One way we could determine must-have screen sizes is from analytics.gov. Some initial links below:

- https://analytics.usa.gov/data/live/screen-size.csv
- https://analytics.usa.gov/data/live/screen-size.json

Identifying these **must-have** device sizes, will also allow us to understand what initial mobile breakpoints we need.

Please let me know if you have any questions! Thank you!

**Comment by glennettec** [comment]
@vim-usds see [this ticket for updated browser](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/490) stats by breakpoint values/browser size/ operating system/browser/users from combineed DOE & EPA sites from 1/1/21-8/7/21. 

I will run another report using EPA ejscreening tool and DOE energy justice tools as filters because it will give us a better understanding of priorities the CEJST.
