### ISSUE TITLE
As a J40 developer, I want to be able to generate an aggregate of the score for zoom levels 0 - X, so that the map renders faster

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#332]
**Description**
We want to add a post-score ETL that takes the output of the score and using `geopandas` does aggregation of the CBG-level score into a tract-level score.

**Solution**
We can use an [approach similar to this](https://github.com/usds/justice40-tool/blob/60934322b4e082d24630771ac5d5daa339a89c55/score/ipython/Score_Dissolve_Script.ipynb) to generate a new score CSV.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [x] Add a national geojson file as output of the `census-data-download` output
- [ ] Create an ETL Python file that applies the Geopandas dissolve is applied and output usa-low
- [x] Merge the national score with state geojson and output usa-high

**Definition of "Done"**
- [ ] ETL Python file for Geo Scores

**Comment by esfoobar-usds** [comment]
Here's the latest [Jupyter Notebook](https://github.com/usds/justice40-tool/blob/5cd75cb807a5547ace51e2d8b5f38748153df496/score/ipython/Score_Dissolve_Script.ipynb) from @NatHillardUSDS

**Comment by switzersc-usds** [comment]
Code complete; one outstanding issue with missing block groups.
