### ISSUE TITLE
As a data engineer, I want to try out different lower zoom level data bucketing techniques, so that I can balance accuracy and performance

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#337]
**Description**
After issue [#209](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/209) , we now have a map representation of tiles for zooms less than level 5. Our initial way of doing this was by bucketing into tracts based on mean score values, then bucketing these tracts into tract buckets. This was initially meant to address overall performance problems with the data. 

However, while performant, this results in block groups going into and out of prioritized state as you zoom further, which can be misleading and/or disorienting. 

**Solution**
We should try out a few different means of improving lower zoom-level presentation of data such that it balances performance and accuracy.

**Describe alternatives you've considered**
- Using just the mean, we have a lot of regions that go into and out of prioritized state as you zoom past level 7. This can be a bit disorienting.

**Tasks**
- [ ] Try out median
- [ ] Try modifying number of buckets
- [ ] Try bucketing values differently, perhaps based on prioritized/not prioritized state?
- [ ] Perform bucketing differently based on size of feature

**Definition of "Done"**
We have tweaked our tile generation process such that we have found an algorithm for bucketing values that is both acceptably performant and deemed representative of data for lower zoom levels.

**Comment by BethMattern** [comment]
We already have working zoom levels. Want to do more testing / usability / research before determining if this is needed.
