### ISSUE TITLE
As a frontend developer, I want to regularly test key browser and map performance events, so that I can know when regressions have occurred

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#340]
**Description**
We should be regularly testing and reporting on performance metrics in our app and map. 

**Solution**
We need to incorporate regular performance testing into our CI/CD workflow. 

**Describe alternatives you've considered**
- Not testing performance at all leaves us open to regressions

**Links to user research or other resources**
- [Here](https://github.com/usds/justice40-tool/tree/client_perf/performance) is an earlier attempt, using puppeteer to hook into chrome dev tools 
- [Here](https://github.com/usds/justice40-tool/blob/client_perf/client/mapbox.js#L149) is an example of using `window.performance.mark` on a mapbox map to capture key events

**Open Questions** 
- Which tool should we use? 
    - Puppeteer overlaps pretty heavily with Cypress, but Cypress recommends against using it for perf testing. There's also [cypress-audit](https://www.npmjs.com/package/cypress-audit) , which may be helpful also if it works

**Tasks**
- [ ] Instrument key performance events with `performance.mark`. At very least the following:
    - [ ] Map load
    - [ ] Map style load
    - [ ] Page load
    - [ ] Map idle
- [ ] Measure timing between these marks, start by logging to file
- [ ] Add github action to incorporate this check into CI/CD, and check for regressions on each pull request

**Definition of "Done"**
- [ ] We have key performance tests being run on all PRs
