### ISSUE TITLE
[SPIKE] As a J40 developer, I want to write Unit Tests for etl_score_post, so that tests are run on each commit.

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#341]
**Description**

Update: changed this scope to just be fore etl_score_post instead of all data pipeline classes. 

We want to make sure any code updates don't break the ETL processes or Score generation, so we will be writing tests that are ran via Github actions on every commit to the codebase.

This card is just for the spike to figure out the pattern (and any refactors needed) to get unit tests going, for example an initial ETL test suite (we need 11 total, one for each source we're ETLing). 

**Solution**
We will write `pytest` modules with small data fixtures and assert that the ETL processes, including the score generation, output the right values and columns.

**Describe alternatives you've considered**
None

**Links to user research or other resources**
None

**Tasks**
- [ ] Review current draft PR from Nat
- [ ] Determine direction for any needed data-pipeline refactor
- [ ] Create tickets for adding unit tests

**Definition of "Done"**
- [ ] Create new, specific testing-backend tickets for adding unit tests
- [ ] Potentially create a refactor pull request if needed

**Comment by switzersc-usds** [comment]
@NatHillardUSDS has written the first one of these (still in progress). We want to break these out into smaller tickets so it's easier to tackle one at a time / simultaneously. We think each ETL test suite will be about 1 day's worth of work. We have 10 more to do.

We want to get to a good pattern that is reusable for future tests, and then de-prioritize finishing these off for now until we know which data sources are critical for the score and therefor require tests.
