### ISSUE TITLE
Update About page to match Sprint 4 design and content

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#348]
**Description**
The content for the About page has been updated to reduce the amount of text, and layout has been changed as well. The site should be updated accordingly.

**Links to user research or other resources**
@janelien confirm when designs for Sprint 4 are ready 

**Tasks**
- [ ] Update About layout
- [ ] Update About text
- [ ] (to confirm with Jane if this is the behavior, About page should be the landing page

**Definition of "Done"**
 - [ ] All content and layout updates as provided by Jane have been incorporated into the site. There may still be minor tweaks to content and bug fixes, etc. later.

**Comment by janelien** [comment]
Designs under Sprint 4:
J40_Sprint 4_About
J40_sprint4_mobile_about
