### ISSUE TITLE
As a repo contributor, I want to understand how large decisions are made, so that I can contribute to making them myself.

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#35]
**Description**
We should propose and document a process for Architecture Decision Records to make it easier to contribute to larger decisions on this project. 

**Solution**
Use a Meta-ADR to document an ADR Process

**Describe alternatives you've considered**
* Unilateral Decision-making
* Not documenting at all 

**Tasks**
- [x] Create diagram for proposed process
- [x] Create Pull Request for ADR describing process
- [x] Email asking feedback

**Definition of "Done"**
- [ ] ADR describing process has been merged
