### ISSUE TITLE
Update the Explore the tool page to reflect Sprint 4 design and content (excluding side panel).

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#350]
**Description**
Updates to the text, layout (for example, color key and download link locations), and where text is shown (for example, CGG details in side panel vs. pop up) have been made to the Explore the tool page design to improve usability and understandability. Some tweaks to the content and bug fixes, etc. might still be needed later, but we should update the site to reflect this latest set of updates.

Side panel work is being done in a separate issue.

**Links to user research or other resources**
@janelien to confirm when designs for Sprint 4 are good for devs to start using.

**Tasks**
- [ ] Jane finalize for Sprint 4 Explore the tool designs and confirm 
- [ ] Update layout on Explore the tool page
- [ ] Update content on Explore the tool page

**Definition of "Done"**
Content and layout on site matches Sprint 4 designs

**Comment by janelien** [comment]
Designs under Sprint 4 - "J40_Sprint 4_About" & "J40_sprint4_mobile_about"

**Comment by vim-usds** [comment]
Tasks

- [ ] Move legend
- [ ] add tool tip to legend
- [ ] mobile view
- [ ] test tool tips on mobile view
- [ ] Rename header
- [ ] Remove download box
- [ ] add link to download file
- [ ] change text treatment on How you can help
- [ ] bullet list less bold
- [ ] not prioritized no bubble

**Comment by vim-usds** [comment]
@janelien  Some questions:

1. The right side of the legend is slightly indented from the right alignment of the page. Assuming this is intentional and by design.
2. Sneaking a peak at Sprint 5, it shows that the limited data sources was moved down and above right above the map. Do we know if this is finalized and if it can be done now?

**Comment by janelien** [comment]
Vim and I met to discuss the designs. Some notes from the discussion:
- The legend (color key) is aligned to the 12 column grid and the map is supposed to be full width with 20px of white space on each side (to allow for scrolling). Current build has the map constrained to a certain width. Having the map go to full width minus 20px on each side may be covered when the mobile readiness ticket (#268) is being worked on but is not an ask for this particular ticket.
- "Limited data sources" alert is moved down to be right above the map. This was a revision in response to difficulty having it under the header. 
- We'll revisit responsiveness at wider browser widths, along with mobile/tablet breakpoints, in a later discussion (with ticket #268), but we both agree that constraining body text is helpful to limit line length (and increase skim-ability/readability).

**Comment by vim-usds** [comment]
Status:
Changing tooltip position on mobile unsuccessful 👎 
- [ ] ~fix tooltip position on mobile~
- [ ] ~fix legend position~
- [ ] ~add windowResize Hook~
- [ ] ~add link to download file~

Tasks remaining:
- [ ] add intl to HowYouCanHelp
- [ ] add intl to MapWrapper
- [ ] add intl to cejst page

Add this to a bug for areaDetail component:
- [ ] useWindowSize hook to render map on mobile (w/o refresh)
- [ ] not prioritized = no bubble
- [ ] fix areaDetail console warning (re-run tests/ snapshots) on unused indicator style

**Comment by vim-usds** [comment]
- [ ] add condensed trusswork
- [ ]  add intl to HowYouCanHelp
- [ ] add intl to MapWrapper
- [ ] add intl to cejst page
