### ISSUE TITLE
Update the Data & methodology page

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#351]
**Description**
Updates have been made to the layout and content of the Data & methodology page to improve usability and understandability, as well as discoverability of the CBG list download link. There may still be tweaks to content and bug fixes, etc. but the site should be updated to reflect the updated Sprint 4 designs.

**Links to user research or other resources**
@janelien to confirm if Data & methodology designs are ready

**Tasks**
 - [ ] Jane confirm Sprint 4 designs
 - [ ] Dev ensure packed download link (additional location that people can download list) matches design spec
 - [ ] Dev ensure updated layout for dataset cards and how the score is calculated matches design
 - [ ] Dev ensure content matches design spec

**Definition of "Done"**
Sprint 4 design updates incorporated into site

**Comment by janelien** [comment]
latest methodology page designs

![J40_Sprint 4_Methodology.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/b2aa327a-b204-4f93-bf03-54cbc69eac62)

![J40_sprint4_mobile_methodology.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/224b0006-93fc-43b6-84a5-6fe6c3a4b3bb)

**Comment by vim-usds** [comment]
This might be done as there's a separate ticket to add the methodology page here:

https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/480

**Comment by janelien** [comment]
I checked it out on this link: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/methodology/. Looks good to me!
