### ISSUE TITLE
Update the Contact page to match Sprint 4 design

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#352]
**Description**
We have updated content and layout change to the Content page as part of overall improving site usability and understandability. There might still be content tweaks later, but the Contact page should be updated to reflect the latest.

**Links to user research or other resources**
@janelien confirm Sprint 4 design mockups are ready for devs to use

**Tasks**
- [ ] Jane confirm Sprint 4 design mockups are ready for devs to use
- [ ] Dev update Contact content
- [ ] Dev remove Get Involved on the side - this is treated differently now in the About page design

**Definition of "Done"**
Site matches Sprint 4 design.

**Comment by janelien** [comment]
latest contact page designs

![J40_Sprint 4_Contact.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/fcd3211b-4517-4094-a707-e1ea156462fc)

![J40_sprint4_mobile_contact.png](https://images.zenhubusercontent.com/60998bc7b85eebae77bd2048/5f22735b-9072-4ead-aacc-3970c5ff81ad)

**Comment by BethMattern** [comment]
We decided to have only one email address for this page and it has been created - screeningtool.feedback@usds.gov

**Comment by switzersc-usds** [comment]
Jane and Tom will discuss this today

**Comment by janelien** [comment]
Could I please get a link to where I should look? I was looking here: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/contact/ but it doesn't have this particular update (two emails are listed).

**Comment by janelien** [comment]
Looks good now.
