### ISSUE TITLE
As a developer, I want to have population density in the data, so that I can understand the difference between urban and rural communities.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#355]
**Description**
We currently have scores that rank order each community (Census Block Groups). One can map each community to either Rural or Urban. We want to know what the distribution of the rank ordering is across urban and rural communities. Some starting questions might be:

1. Of the communities identified as "disadvantaged" what percent are urban vs rural (how does that compare to the inherent percentage of urban vs rural CBGs)?
2. Of urban areas, how many are identified as "disadvantaged"?
3. Of rural areas, how many are identified as "disadvantaged"?

Note, this literally applies to scores that generate a classification (1 or 0) of disadvantaged, which admittedly are most of the scores. For score that produce a rank ordering, will need a different definition, like mean or some other way to measure the distribution.

**Links to user research or other resources**

**Tasks**
- [x] Query map of CBGs to Urban vs Rural from Geocorr. Save download link to add officially to ETL process later
- [x] Manually place CSV file that maps CBGs to Urban / Rural locally to computer
- [x] Manually generate scores across all CBGs (does the scoring_comparison notebook generate these flat files?)
- [ ] Load files into a Jupyter Notebook; Map CBGs to Urban vs Rural
- [ ] Do the analysis!
- [ ] Check in with Shelby to make sure this actually makes sense
- [ ] Add officially to the ETL scripts to make sure it's reproducible moving forward. 

**Definition of "Done"**

**Relevant Links**
1. See this [relevant Slack Thread](https://usds.slack.com/archives/C0222FBGQ65/p1631564251076300) for Lucas's PR
1. See this [relevant Slack Thread](https://usds.slack.com/archives/C0222FBGQ65/p1631302674043000) for finding files on AWS.

**Comment by VincentLaUSDS** [comment]
The UI will look something like this for Urban/Rural
![image](https://user-images.githubusercontent.com/79174257/133484421-78e9c129-2af2-4f04-9a19-84ae6c2df67c.png)

**Comment by VincentLaUSDS** [comment]
Slack thread on running code: https://usds.slack.com/archives/C0222FBGQ65/p1631808402174600
