### ISSUE TITLE
As a developer, I want to understand and document tile hosting options, so that I can make an informed decision about how to vend map data

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#36]
**Description**
We should do time-boxed research/have time-boxed discussions about which tile server to use based on the features we need. 

**Solution**
Create an ADR based on outcome of research for a path forward with a tileserver.

**Describe alternatives you've considered**
- Need to research alternatives further to give a good list here
- Another alternative is a fully-custom tileserver backend, but it seems there are a number of options that have a number of features.

**Tasks**
- [ ] Document tileserver needs
- [ ] Research tileserver options
- [ ] Have conversations about available options
- [ ] Create ADR documenting decision
- [ ] Create followup ticket to handle implementing this solution

**Definition of "Done"**
- [ ] Merged ADR
- [ ] New ticket for implementation

**Comment by NatHillardUSDS** [comment]
Hi folks - 
Thanks for the comments! Indeed that's where we documented our current FE decision. 

As for this issue, focused around the tile server BE, it may turn out that we don't need this particular card, in that we may not need our own specific tile server. We are discussing partnering with geoplatform.gov at present - you can follow along and participate as that discussion develops over [here](https://github.com/usds/justice40-tool/issues/18) as this develops.
