### ISSUE TITLE
As a FE developer, I want consistency in page layout across the app, so that its clear how to make future sizing decisions

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#363]
**Description**
Right now, we're using a mix of the USWDS [layout grid](https://designsystem.digital.gov/utilities/layout-grid/), [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), and raw px/em values. 

**Solution**
We should choose a system or systems, make existing page layouts consistent, and develop guidelines for future usage. 

**Describe alternatives you've considered**
- As things stand, it's not clear how to style a new page. 

**Tasks**
- [ ] Audit existing page styling mechanisms
- [ ] Based on this, and best practices, write out guidelines for how to layout elements on the page, and store these in a readme
- [ ] Make necessary changes to bring our page layout in line with these guidelines.
- [ ] Fix header
- [ ] Fix footer (see #564)
- [ ] FIx main content
- [ ] Fix "USA header"
- [ ] Fix Alerts (see #562)

**Definition of "Done"**
We have written out guidelines for how to layout pages and made our page layouts consistent with these.

**Comment by switzersc-usds** [comment]
Note that Tom has started tackling some of this. Vim and Tom will touch base on more specifics and knock out the little things that are left.

**Comment by switzersc-usds** [comment]
This may be done. Any outstanding issues are probably addressed in #571. I'm closing this for now and if we find specific layout issues we will create new bug issues for those.
