### ISSUE TITLE
As an EVCM, I want to be able to see a full-screen version of the map, so that I can make out smaller features more easily

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#365]
**Description**
Our tool's map currently only takes up half the page. We should offer the commonly-offered option to make the map full screen. 

**Solution**
Mapbox offers an out-of-the-box full screen control we can use which is simple to implement and low risk. 

**Describe alternatives you've considered**
- We 

**Links to user research or other resources**
- https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/  - mapbox docs
- https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control - React-map-gl wrapper
- https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/23c674/en/cejst/?flags=gl,fs - our current flagged version of this (needs refinement!)

**Open Questions**
- The OOB solution does not work for iphone, so we will need another solution. Mobile safari on a phone does not allow the FullScreen API, as seen here: https://caniuse.com/fullscreen . Mapbox hardcodes the check for this API [here](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/control/fullscreen_control.js#L74). This might be sufficient? 
```#map {
    height: 100%;
    width: 100%;
}
#map-container {
    height: 100vh;
    width: auto;
}```

**Tasks**
- [ ] Design to create spec
- [ ] Dev should harden [code](https://github.com/usds/justice40-tool/blob/main/client/src/components/J40Map.tsx) that currently does this 
- [ ] We should ensure this works with side panel and other controls 

**Definition of "Done"**
We have a button users can hit to make the map full screen.
