### ISSUE TITLE
Implement short description of indicator in sidebar

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#367]
**Description**
We need to give a short description of each indicator in the sidebar. Ideally this comes from the YAML file for each indicator. 

**Tasks**
- [ ] Decide how to represent this in the YAML file
- [ ] Finalize copy for short descriptions
- [ ] Define contract between frontend/backend and where is handoff
- [ ] Test!
- [ ] Implement front end code to pull this field from JSON generated in data-pipeline

**Definition of Done**
-  Website shows short descriptions for each indicator in sidebar

**Comment by vim-usds** [comment]
https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/428
