### ISSUE TITLE
As an open source community member, I want to read open source process docs in my native language, so that I can understand the processes and more effectively contribute.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#37]
**Description**
Juan Parras raised the great point in our kickoff call that we should be translating our process docs (not just our published website) into the languages of communities impacted by this work and whom we want to ensure are included in the open source processes we are building. 

**Solution**
Provide translations of our process documentation in prioritized languages. Spanish at a minimum, and we should identify others needed.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
Translations of the following docs: 

- [x] README
- [x] CONTRIBUTING
- [x] Code of Conduct
- [ ] Data Roadmap Process
- [ ] Locations in directory structure (i.e. /EN and /ES) created to store .md files
- [ ] Issue templates (e.g. have English and Spanish in the template)

**Comment by katherinedm-usds** [comment]
Update that translation has been officially kicked off with the DOS, and I asked them if they could provide by COB this Friday June 18th, at least for the .md files. 

That means we'd need an /ES directory or some place to put these, @switzersc-usds could you please advise where these should go in the repo when ready? Not super urgent but seems like it would be good to get the translations up when we receive.

One additional note, I didn't have Data Roadmap Process translated yet.

**Comment by switzersc-usds** [comment]
Expecting translations 6/22

**Comment by katherinedm-usds** [comment]
[https://app.zenhub.com/files/358242767/8f33f6f4-7739-482c-9bb8-50f0bc671669/download](https://app.zenhub.com/files/358242767/8f33f6f4-7739-482c-9bb8-50f0bc671669/download)[https://app.zenhub.com/files/358242767/4e68a44f-a21e-4233-bb24-2f3d35ef95b0/download](https://app.zenhub.com/files/358242767/4e68a44f-a21e-4233-bb24-2f3d35ef95b0/download)[https://app.zenhub.com/files/358242767/bc57b671-9691-4fd7-815d-8fddbd0b6607/download](https://app.zenhub.com/files/358242767/bc57b671-9691-4fd7-815d-8fddbd0b6607/download)[https://app.zenhub.com/files/358242767/ceae591a-e403-4397-82ad-91268c680289/download](https://app.zenhub.com/files/358242767/ceae591a-e403-4397-82ad-91268c680289/download)[https://app.zenhub.com/files/358242767/ddb73f70-b699-4f63-8889-0a7d62d4cfcf/download](https://app.zenhub.com/files/358242767/ddb73f70-b699-4f63-8889-0a7d62d4cfcf/download)

**Comment by katherinedm-usds** [comment]
We received translations! 

For README, CODE OF CONDUCT, CONTRIBUTING, see attached .txt files for unformatted text, and there are .docx that can be used to see the formatting, though unfortunately it still needs the .md syntax for formatting when it goes into a .md file. It looks like the translation team went ahead and translated MAINTAINERS and LICENSE since they were going through the GH repo themselves, though I didn't specifically ask for this, but since we have it we can use it.

The Issue Templates translated into Spanish are attached as .docx.

@switzersc-usds LMK if you want me to get these into the repo and issue templates, for the .md files just point me to the directory.[https://app.zenhub.com/files/358242767/76458ade-6814-423b-b1f1-215db01af058/download](https://app.zenhub.com/files/358242767/76458ade-6814-423b-b1f1-215db01af058/download)[https://app.zenhub.com/files/358242767/913114f2-a7e3-4ea2-8f80-ea1a6b746f1e/download](https://app.zenhub.com/files/358242767/913114f2-a7e3-4ea2-8f80-ea1a6b746f1e/download)[https://app.zenhub.com/files/358242767/a53c5085-fb6d-4968-ba1a-23ffa221bae7/download](https://app.zenhub.com/files/358242767/a53c5085-fb6d-4968-ba1a-23ffa221bae7/download)[https://app.zenhub.com/files/358242767/2b9ab45d-7935-4695-a589-784611a882cc/download](https://app.zenhub.com/files/358242767/2b9ab45d-7935-4695-a589-784611a882cc/download)[https://app.zenhub.com/files/358242767/6193f6f4-18e3-4869-b57c-a9ed467a2143/download](https://app.zenhub.com/files/358242767/6193f6f4-18e3-4869-b57c-a9ed467a2143/download)

**Comment by katherinedm-usds** [comment]
These are the translated issue templates

[https://app.zenhub.com/files/358242767/3a6e424f-cb4e-4ad5-b99c-3be49cb07d9a/download](https://app.zenhub.com/files/358242767/3a6e424f-cb4e-4ad5-b99c-3be49cb07d9a/download)[https://app.zenhub.com/files/358242767/7e070979-ae17-434a-be8c-dc1516ffdaf0/download](https://app.zenhub.com/files/358242767/7e070979-ae17-434a-be8c-dc1516ffdaf0/download)[https://app.zenhub.com/files/358242767/2e8049e9-6a85-4798-94ab-171d07545971/download](https://app.zenhub.com/files/358242767/2e8049e9-6a85-4798-94ab-171d07545971/download)[https://app.zenhub.com/files/358242767/c66c9cc2-096d-4488-9c17-a397fda3060e/download](https://app.zenhub.com/files/358242767/c66c9cc2-096d-4488-9c17-a397fda3060e/download)
