### ISSUE TITLE
Data Roadmap

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#38]
## Description
We should define the process for the intake, prioritization, and voting on datasets for inclusion in the Justice40 Tool.

## Definition of Done
- [ ] Process has been defined
- [ ] We have sent one dataset through the entire process end to end
- [ ] Data pipeline is hosted and publicly accessible
