### ISSUE TITLE
As a user, I want to see the cumulative impact score and associated info for communities that are not prioritized, so that I can learn more about how communities are scored

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#383]
**Description**
The current version of the tool does not let you select non-prioritized or threshold CBGs to see what their cumulative index score percentile, non-prioritized Categorization, indicators and associated percentiles for those, etc. 

**Solution**
For non-prioritized CBGs, enabled CBG selection and side panel information similar to prioritized and threshold communities

**Describe alternatives you've considered**

**Links to user research or other resources**
- @janelien confirm design, so it's clear what the Categorization should look like on the side panel for non-prioritized communities, etc.

**Tasks**
 - [ ] @janelien confirm design
 - [ ] Dev enable non-prioritized CBG selection
 - [ ] Dev implement valid score data to be populated in side panel matching design

**Definition of "Done"**
Valid cumulative index score percentile, categorization, CBG ID, indicators and percentiles shown for all non-threshold CBGs

**Comment by NatHillardUSDS** [comment]
Pushed the first part of this change just now , which allows you to interact with non-prioritized communities:
You can test this here: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/ccb080/en/cejst/

We still need to add the side panel as well to complete the above requirements, but this is the first part

**Comment by janelien** [comment]
Design is under Sprint 4 so it's next to the other side panel designs but titled:
J40_Sprint 5_map_not prioritized

**Comment by janelien** [comment]
Met with Vim and discussed a few small edits. 
- Changing from title case to sentence case (for Housing burden and Linguistic isolation)
- Unemployment to be 'Unemployment rate'
- Changing mobile breakpoint to 414px. It's currently at 400px, but 400px doesn't work for iPhone 11s. This would be a temporary fix with a more permanent fix being tackled in the mobile readiness ticket. 

We looked at breakpoints and 800px would be good for pretty much all tablets/mobile devices. Tablet view would benefit from being the same as the mobile view. 

Overall, it's looking great!

**Comment by janelien** [comment]
A bit more of what we looked at for reference:

https://www.browserstack.com/guide/ideal-screen-sizes-for-responsive-design

According to the Worldwide Screen Resolution Stats (Jan 2020 – Jan 2021), the most commonly used resolutions across mobile, desktop, and tablet are:

1920×1080 (8.89%)
1366×768 (8.44%)
360×640 (7.28%)
414×896 (4.58%)
1536×864 (3.88%)
375×667 (3.75%)


and this: https://www.icwebdesign.co.uk/common-viewport-sizes

**Comment by NatHillardUSDS** [comment]
whoop - were these comments on the correct ticket / did you mean to put them over on https://github.com/usds/justice40-tool/issues/288 ?

**Comment by janelien** [comment]
yep! just moved them over!
