### ISSUE TITLE
As a non-engineer community member, I want to suggest a new idea for a dataset, so that I can participate in the data pipeline

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#39]
**Description**
We should create a means for non-engineer community members to suggest new ideas for a dataset, using tools familiar to them. 

**Solution**
To make it easy for non-engineer members of the public and advisory bodies such as the WHEJAC to submit suggestions for data sets, we will configure a Google Form that maps to the schema of the data set files. It probably makes the most sense to autogenerate the Google Form out of the Yamale schema for data set descriptions and the accompanying field description file; this will help keep the schema and the Google Form in sync.

This will enable members of the public to fill out a simple form suggesting data without needing to understand Github or other engineering concepts.

At first, these responses can just go into a resulting Google Sheet and be manually copied and converted into data set description files. Later, we can write a script that converts new entries in the Google Sheet automatically into data set file descriptions and opens a pull request. That work is tracked in [this ticket](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/60)

**Tasks**
- [x] Setup official Google Sheet with appropriate schema, share publicly
- [x] Create a Google Form to capture additional responses

**Definition of "Done"**
- [x] Sheet created and circulated
- [x] Form public

**Gotchas**
- [ ] Ensure we're compliant with PRA restrictions

**Comment by switzersc-usds** [comment]
Status: Google script that generates the form is done. In the future we will work on a way to automatically update the form from the YAML schema (and ensure the URL stays the same).

**Comment by switzersc-usds** [comment]
Next steps for QA: Get team feedback, review for PRA compliance. @KameronKerger is the QAer.

**Comment by esfoobar-usds** [comment]
- Public Form lives [here](https://forms.gle/T4rdcfZ4pSs4CU4B9)
- Google Sheet (public for comments, auth for editing) [here](https://docs.google.com/spreadsheets/d/14ZuTjasiO58XqDDGUkG7ZjBAbGIlqdwsU-tdH8741lE/edit#gid=1181359855)

Please read the following caveats below:
- The Google Form is generated by [running this script](https://github.com/usds/justice40-tool/blob/0f059c0cd1cc20502486cf9b4f25f90be7976235/data-roadmap/data_roadmap/data_set_descriptions/google_form_gen.js) on a Google Apps Script on the Justice 40 Google Drive. I haven't found a way that we can run this script programmatically from Github Actions.
- Each time the script is run, a new form (and a new URL) is created as well a new Google Sheet with a random UUID. If changes are made to the script, we would need to be aware of the previous sheets contents

**Comment by switzersc-usds** [comment]
Existing descriptions for fields here: https://github.com/usds/justice40-tool/blob/main/data-roadmap/data_roadmap/data_set_description_field_descriptions.yaml

**Comment by switzersc-usds** [comment]
To do: Write a description to go at the top of the form explaining what the form is, how to use it, how it will be used, and a link to the spreadsheet where you'll see your submission populate. We should also ask people here to look at the spreadsheet first to make sure the dataset hasnt been submitted yet. 

I can do this Monday morning around 9am. If anyone has time and wants to do this beforehand, go for it!

**Comment by janelien** [comment]
Here are my thoughts: 

name: A short name for the data set. 

source: The URL / website where this data set can be found.

relevance_to_environmental_justice: Reason(s) why this data set is important for the environmental justice community (e.g. helps identify an EJ community)

spatial_resolution: How specific does this data set get?

public_status: Has this data set gone through a public release process?
[add a 'Not Sure' option]

sponsor: Who is providing and maintaining this data? (e.g. a federal agency, a specific organization) 

subjective_rating_of_data_quality: Has this data set been vetted? 

estimated_margin_of_error: Estimated margin of error on measurement, if known. 

known_data_quality_issues: Are there any known issues with this data set?

geographic_coverage_percent: What percentage of the United States and US territories does this data set cover? This can be an estimate.

geographic_coverage_description: Tell us more about the geographic coverage. 

data_formats: [can you add an 'Not Sure' option?]

last_updated_date: When was the data last updated or refreshed? (Use format YYYY-MM-DD. If exact date is not known, use YYYY-01-01.)

frequency_of_updates: How often is this data updated? 

documentation: Please include any links to documentation.

[Can it be relabeled as 'Can data go in the cloud?']
data_can_go_in_cloud: Some datasets can not legally go in the cloud

[Can this be relabeled as 'Additional Information'?]
discussion: Please include additional information around peer review, data availability (is it available from multiple sources?), any legal considerations, accreditation, etc.

**Comment by katherinedm-usds** [comment]
Jane's recos are great!

To go along with Jane's reco :
subjective_rating_of_data_quality: Has this data set been vetted?
I think for now this is good, and can answer options be "Yes", "Somewhat", "No", "Not sure"?

For this one I'd say instead "Can his data go into cloud data storage? Sometimes there are restrictions on what can be stored in the cloud.'
data_can_go_in_cloud: Some datasets can not legally go in the cloud

**Comment by switzersc-usds** [comment]
Thanks for the descriptions, y'all!

So, this is my understanding of what we need to do today, by 5pm ET latest (OSG chat) but ideally by 2pm ET so we can show this workflow to Cecilia.

- [ ] Add field descriptions to form
- [ ] Add form description to top of form 
- [ ] Move existing backlog spreadsheet to the new spreadsheet
- [ ] Remove “required” from all fields except name and URL
- [ ] Add optional “email address of submitter” field
- [ ] Test out workflow 

Is that accurate? Anything else?

**Comment by switzersc-usds** [comment]
Description draft for top of form:

> Thank you for participating in the Justice40 open data roadmap! Use this form to submit individual data sets to be considered for the data roadmap of the Justice40 Climate and Environmental Justice Screening Tool. Once the data set is submitted, you can view it in our submission tracking spreadsheet here (link). 
> 
> Please try to fill out as many of the details below as possible for the data set you are submitting. If you do not know the value for a given field, you can leave it blank, and someone from our team or from the open source community will help research to figure it out and will update the spreadsheet accordingly. Instructions for suggesting updates to the spreadsheet are available in the second tab of the spreadsheet. Once a data set has been fully researched, the White House Environment Justice Advisory Council (WHEJAC) will vote on whether and how to prioritize the data set for inclusion in the tool. 
> 
> If you have any questions, please email us at justice40open@usds.gov.

**Comment by switzersc-usds** [comment]
Draft text for the "How to contribute" tab in the google sheet: 

# How to contribute to this spreadsheet				
Thanks for your interest in helping us grow the data roadmap for the Justice40 Climate and Environmental Justice Screening Tool! We could use your help in adding and updating data set submissions to be considered for our roadmap. Once a data set is added and fully investigated (i.e. all quantitative columns have been filled out for it in this spreadsheet), the White House Environmental Justice Advisory Council (WHEJAC) will vote on whether and how to prioritize the dataset in inclusion in the tool. 				
				
## 1. Adding a data set				
Please use this Google Form to submit a data set to this spreadsheet: (link)		
				
## 2. Updating a data set				
If you see a data set that has one or more empty values for a column (for example, there is no value for "Spatial Resolution"), you can help us research and fill this out. This may involve downloading a data set and looking at it directly to get an answer, or reading through the data set's documentation. Once you've found the value of the field you're investigating, leave a comment on the specific cell in the spreadsheet with the value. A Justice40 team member will review the comments on a daily basis and update the cell directly with the value you've left in your comment.

**Comment by lucasmbrown-usds** [comment]
@switzersc-usds - re: your checklist, if we remove "required" from all those other fields, we'll also need to update the Yamale schema, since we're essentially maintaining the schema twice here. That sounds fine to me I just want to make sure we're tracking it.

**Comment by esfoobar-usds** [comment]
And to @lucasmbrown-usds point, is it okay if I update the descriptions above in the [data field descriptions YML file](https://github.com/usds/justice40-tool/blob/Google-Form-Data-Set-Ingestion-Script/data-roadmap/data_roadmap/data_set_description_field_descriptions.yaml), since it's the source of truth @switzersc-usds?

**Comment by lucasmbrown-usds** [comment]
> is it okay if I update the descriptions above in the data field descriptions YML file

That sounds valuable to me @esfoobar-usds !

**Comment by KameronKerger** [comment]
Rachel has been emailed. We should probably modify and include some of the USDS consent language here.

Thanks for taking the time to speak with us! You have been asked to participate in a feedback session conducted by the U.S. Digital Service. This form explains how we might use the information that you provide in this feedback session. Signing this form and participating in this session is entirely voluntary. You may stop the session at any time. Please read this form carefully and ask any questions you may have before agreeing to participate.

We might use or share things we learn during this session in reports, online, and in presentations.

Consent

By signing this form, I give my permission for the U.S. Digital Service to use (please check all that apply):

 Written notes of verbal statements
 My real name
 Recorded voice
 Screen recordings
 Pictures of me participating in the session
 Video recording of the interview
Statement of consent I consent to take part in this session and to have any information I provide be used in the manner described above. I understand that I will receive no compensation and waive all claims for compensation from the U.S. government in exchange for my participation in this research. I expressly release the U.S. Digital Service from and against any and all claims that I have or may have for invasion of privacy, defamation, or any other cause of action arising out of the production, distribution, display, or publication of the results of the project, so long as they are used in the manner indicated above. I have read the above information and received answers to any questions I have asked.
