### ISSUE TITLE
[Spike] Set up Cucumber/Gherkin to be used in the front end test suite

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#390]
**Description**
We should adopt Cucumber/Gherkin for describing test cases, to make it easier to write and maintain them and to create a common vocabulary around testing and test scenarios. This will make QA a lot easier and faster and make it easier to maintain the codebase.

**Solution**
We should setup [cypress-gherkin-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) to bridge cypress and gherkin for describing test cases. 

**Describe alternatives you've considered**
- Using cypress out of the box helps engineers, but is less visible to non-engineers / makes it harder to write and maintain test suites. 

**Links to user research or other resources**
- https://github.com/TheBrainFamily/cypress-cucumber-preprocessor
- https://cucumber.io/
- https://cucumber.io/docs/gherkin/

**Tasks**
- [x] Adopt gherkin-cypress-cucumber
- [x] Setup a test or two to show how it would work 

**Definition of "Done"**
- [x] An initial pattern for creating more gherkin tests
- [x] More fleshed out issues to write remaining gherkin tests

**Comment by vim-usds** [comment]
Status update:

tasks:

- [ ] initial set up of cucumber/gherkin integration
- [ ] added title page to each page
- [ ] refactor each page (mostly cejst) to remove any dependencies on local css (tech debt)
- [ ] move title string to intl
