### ISSUE TITLE
As an engineer community member, I want to suggest a new idea for a dataset, so that I can participate in the data pipeline

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#40]
**Description**
We should create a means for engineer community members to suggest new ideas for a dataset, using tools familiar to them.

**Solution**
To start, we'll create a folder in the appropriate repository that can house YAML files, one per data set. Each file will describe the characteristics of the data.

We'll use a Python-based script to load all the files in the directory, and then run a schema validator to ensure all the files have valid entries.

For schema validation, we propose using Yamale. This provides a lightweight schema and validator, and integrates nicely with GitHub actions.

If there's an improper format in any of the files, the schema validator will throw an error.

As part of this milestone, we will also set this up to run automatically with each commit to any branch as part of CI/CD.

**Describe alternatives you've considered**
- The benefit of using a YAML file for this is that it's easy to subject changes to these files to peer review through the pull request process. This allows external collaborators from the open source community to submit suggested changes, which can be reviewed by the core CEJST team.

**Tasks**
- [x] Create directory structure and README
- [x] Create YAML schema
- [x] Create schema validator
- [ ] Integrate this process into Continuous Integration
- [ ] Create Github issue template to create new dataset suggestion

**Definition of "Done"**
- [ ] Pipeline has been run end to end on a new dataset, including CI integration

**Comment by switzersc-usds** [comment]
@esfoobar-usds I think this is done, at least partially, or should be broken into multiple stories and whatever is left here moved back to the backlog until we're ready to prioritize it. Thoughts?

**Comment by esfoobar-usds** [comment]
We probably should break it, I really didn't touch this card. The CI part for the feed validation is what's missing.

[I've created a new card](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/96).
