### ISSUE TITLE
[SPIKE] As a user, I want the community list package to indicate which version it is and when it was last updated / publish so that I can know if this is a new version from one I may already have.

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#408]
**Description**

As a person on the website I would want the community list package to indicate which version it is and when it was last updated / publish so that I can know if this is a new version from one I may already have.

**Solution**
The download button should indicate which version the download will contain and when it was last updated or published.

**Describe alternatives you've considered**
None

**Links to user research or other resources**

**Tasks**
- [ ] Meet and discuss the approach for score versioning and its side effects on frontend and backend
- [ ] Produce a document that describes the methodology of what a score update entails

**Definition of "Done"**
- [ ] Document is completed that will be the blueprint for frontend and backend tickets

**Comment by KameronKerger** [comment]
suggested mockup (need to discuss version numbering strategy)
<img width="476" alt="Screen Shot 2021-07-29 at 1 05 43 PM" src="https://user-images.githubusercontent.com/77702996/127558707-6ea76b2d-86f5-4475-b98a-d33e32c2206a.png">

**Comment by katherinedm-usds** [comment]
For prelaunch, let's have as a placeholder "Download package v0.1" and the dev work to be possibly automatically generating the "last updated" date - to discuss with dev

**Comment by vim-usds** [comment]
From engineering - there might be a way to turn on versioning on the folder that currently holds the zip file on S3. Then each time the file is updated, it will be given some ID. The app (onLoad) would GET the latest ID and set the version on the UI (as shown on the mock). What also is TBD, is a way to map IDs to versions. The CDNs could add a layer of complexity. Super rough guess is that this could take about ~ 3 to 5 days to develop and test.

Another approach is to wait until an API is created. Getting the version of the download file could be a potential endpoint in the API. This estimate would be less as it places work on the BE.

**Comment by katherinedm-usds** [comment]
Thanks @vim-usds! for visibility, I'd push for this to be worked on in Sprint 6, it's a feature we know we'd want for public beta launch, so would be good to get a sense of timing for this API if that's the preferred route from a dev standpoint. fyi @switzersc-usds

**Comment by esfoobar-usds** [comment]
After talking with the team in backlog grooming, we'd need:
- A markdown file on the top level of the repo with a history of the score versions and what changed on each one
- Tow constants on the [score-etl constants](https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/etl/score/etl_score.py#L13) with what version of the score we're in and the date string
- Add this constant value on the downloadable packet file name (downloadable/Screening_Tool_Data_v1.2.zip)
- @vim-usds to create the frontend ticket to update site when version/date changes in backend

**Comment by switzersc-usds** [comment]
We need to discuss this as a team to flesh out what we're looking for here. We should consider what kind of versioning we need for the data at all stages in the pipeline, not just the final download packet in the UI.

**Comment by switzersc-usds** [comment]
One component of versioning is the score type: A, B, C, etc. Another component is the version of the score type (eg the second version of Score E).

Distinction between public version and internal version. Public version needs to be clear, make sense, and be solid. 

We're going to think about internal versioning needs first (e.g. communicating within the team or stakeholders) and then think about external versioning needs. Right now let's say that when we have a file for internal use, we have the score type + timestamp in the filename. Maybe additional info to reflect state of code (eg 6 chars of  a commit sha).

**Comment by BethMattern** [comment]
For the 9/20 launch we decided to put an as of date on the website text of the download package & the download package file will have a date/time stamp. @KameronKerger will be the person who remembers that these dates/time stamps need to be updated if/when there are changes in the near future.
