### ISSUE TITLE
As a community member, I want to understand what happened with my suggestion for a new dataset.

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#41]
**Description**
Once suggested, we should have a single place where all community members can go to see the current status of a given dataset request. 

**Solution**
Add a script that runs the schema validator on all files and, if successful, posts the results in a tabular format. There are straightforward packages to post a Python dictionary / pandas dataframe to Google Sheets and/or Airtable. As part of this milestone, we will also set this up to run automatically with each commit to main as part of CI/CD.

This will make it easier to filter the data to answer questions like, "which data sources are available at the census block group level"

**Describe alternatives you've considered**
- Doing this in a proprietary tool like ArcGIS hub is not an option given our focus on openness.

**Tasks**
- [ ] Create a script or Github Actions step that converts validated schemas to rows in a table of some sort
- [ ] Integrate this with the CI/CD pipeline
- [ ] Enable filtering on this dataset

**Definition of "Done"**
- [ ] Publicly-available table exists
- [ ] Table is populated automatically when new dataset is added
