### ISSUE TITLE
As a developer, I want to run the whole system with one command (docker-compose up).

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#416]
**Description**
We should be able to run our entire app - frontend and backend - in production mode, with one command.

This would also help us run github actions locally so we know what breaks before we push.

**Solution**
We should dockerize our frontend code in "production" mode (wrapping `gatsby build`), then unite this with our existing backend docker and backend-oriented `docker-compose.yml` such that we can spin up a local development environment `docker compose up` .  

**Describe alternatives you've considered**
- We previously investigated wrapping frontend development mode (ie `gatsby develop`), but ran into various limitations with this. Filed this as a separate issue [here](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/417)

**Out of scope for this ticket**
* This ticket will explicitly cover only prod, not development (see #417 for that)
* This will not yet cover running tests or other checks currently being run by github actions locally (see [#418](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/418) for that)

**Tasks**
- [ ] Dockerize `gatsby build` for the frontend
- [ ] Incorporate this into the top-level `docker-compose.yml` file
- [ ] set up front end env vars for prod and dev
- [ ] Document how this is done

**Definition of "Done"**
* Production site can be spun up and run locally with `docker-compose up`
* Documentation explaining this
