### ISSUE TITLE
Implement long description of indicator on Methodology page

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#429]
**Description**
We need to give a long description of each indicator in the methodology page. Ideally this comes from the YAML file for each indicator.

**Tasks**
- [ ] Decide how to represent this in the YAML file
- [ ] Finalize copy for short descriptions
- [ ] Define contract between frontend/backend and where is handoff
- [ ] Test!
- [ ] Implement front end code to pull this field from JSON generated in data-pipeline

**Definition of Done**
Website shows short descriptions for each indicator in sidebar
