### ISSUE TITLE
(Epic) Initial Dataset and score

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#48]
## Description
In order to get our data processing and scoring pipelines setup, we should prioritize identifying 2-3 datasets, processing them, and combining them into a score. 

## Non-goals
This will not include a UI for now, just a mapping from census block group to score

## Definition of Done:
- [ ] Initial datasets chosen
- [ ] Command-line tool to show score for a given block group
- [ ] Every census block group in the US has a score its constituent parts
