### ISSUE TITLE
[SPIKE] Deeper dive on integrating existing design system into app

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#512]
**Description**
Deeper dive on integrating existing design system into app. The main goal is that dev + design both understand the same library, and that design has clear pathway for picking or creating a design component and dev has clear pathway for incorporating it into app.

Focus on the two main areas causing consistency issues: grid/layout and typography of headings.

**Tasks**
- [x] Vim to deep dive into design system components and share out
- [x] Investigate how to use typography with tokens
- ~[ ] Gina to review SCSS pipeline/implementation with team~
-  [x] Team (dev+design) has a clear understanding of inheritance of style for grid component / layout and typography/heading elements
- [ ] Documentation of our use of the design system + Trussworks
- [ ] Decision made about tools used between dev and design 

**Definition of done**
- [ ] Markdown on Repo with these guidelines or supporting knowledge

**Comment by switzersc-usds** [comment]
Vim working on docs for this now.

**Comment by vim-usds** [comment]
@janelien 

Here's the initial documentation of this. I think we'd want to talk a little more about how design uses USWDS?

https://github.com/usds/justice40-tool/blob/b1efbcdc4910d43675b00b33dc8f53ca3cd7d949/client/DESIGN2DEV.md
