### ISSUE TITLE
As a developer, I want to know what dataset to work on next, so that I can match priorities to those from the community

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#52]
**Description**
We should integrate the dataset proposal process with our ticketing system to keep track of work as it progresses. 

**Solution**
For each data set that is being considered for inclusion soon in the tool, the project management team will create a ticket for "Incorporating ___ data set into the database", with a link to the data set detail document. This ticket will be created in the ticket tracking system used by the open source repository, which is ZenHub. This project management system will be public.

At the initial launch, we are not planning for members of the open source community to be able to create tickets, but we would like to consider a process for members of the open source community creating tickets that can go through review by the CEJST team.

This will help developers know what to work on next, and open source community members can also pick up tickets and work to integrate the data sets.

**Tasks**
- [ ] Setup process by which tickets can be created from approved requests
- [ ] Setup columns and label systems

**Open Questions**
- [ ] Is this a separate project board? 
- [ ] What should the phases be?
- [ ] How can we involve outside assistance in processing datasets (e.g. geoplatform/Zenity)

**Definition of "Done"**
- [ ] Approved datasets are automatically tracked in issue tracking system
