### ISSUE TITLE
As a developer, I want to ingest the FEMA National Risk Index for Natural Hazards (NRI) data set, so that it can potentially be used in the screening tool

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#523]
**Description**
The FEMA National Risk Index for Natural Hazards (NRI) data needs to be available in the screening tool so that it could be visualized on the map, be included in score prototypes, be compared to our score, and/or be included for all census block groups in the csv/excel download file. 

The NRI data identifies communities most at risk to 18 natural hazards. This data is only available at the Census tract level, so for now we would apply the same indicators to all census block groups contained within a census tract.

The source of the NRI data:
](https://hazards.geoplatform.gov/portal/apps/MapSeries/index.html?appid=ddf915a24fb24dc8863eed96bc3345f8)

**Tasks**
- [ ]  Obtain NRI data files
- [ ]  Import the data 
- [ ]  Apply tract-level data to all census block groups contained in that tract 

**Definition of "Done"**
- [ ] NRI data at the census tract level is applied to census block groups so that it is available to be used by the screening tool
- [ ] NRI data is available to be displayed in the map UI
- [ ] NRI data is available to be downloaded in the CSV
