### ISSUE TITLE
As a WHEJAC board member, I want to track general problem areas or data idea so that I don't have to have a specific dataset in mind

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#53]
**Description**
We should add a means of annotating datasets with "problem areas" that describe problems in climate, environmental, and economic justice, in order to allow for higher-level grouping and tracking. This is so that non-data-focused members of the public or the WHEJAC advisory body can suggest we prioritize certain problem areas, with or without ideas for specific data sets that may best address that problem area. For instance, a problem area may be "food insecurity", and a number of data sets can have this as their problem area.

**Solution**
We should add a field in our dataset description that includes "problem area" in some form.

**Open Questions**
Still open as to how to do this:
- [ ] Create a folder for descriptions of problem areas, which contains YAML files that get validated according to a schema
- [ ] Add these as an array in the description of data sets
- [ ] Add labels to the tickets once data sets are tracked in GitHub tickets

**Tasks**
- [ ] Create initial set of labels in some form
- [ ] Change the linter to validate that every data set description maps to one or more known problem areas
- [ ] Enable filtering on these labels in some form

**Definition of "Done"**
- [ ] We have defined a set of problem area labels
- [ ] Problem area labels are applied to all existing issues

**Comment by katherinedm-usds** [comment]
This is on hold until we get clear direction on further engaging with WHEJAC advisors on their input on dataset prioritization and other data related concepts.
