### ISSUE TITLE
As a community member, I want to vote on what data sources should be prioritized next, so that I can have input into the process

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#54]
**Description**
This milestone is currently the least well-defined. It's important that members of advisory bodies like the WHEJAC and members of the public be able to "upvote" certain data sets for inclusion in the tool.

**Solution**
One potential for this is to use the Stanford Participatory Budgeting Platform. Here's an example of voting on proposals within a limited budget.

For instance, going into a quarterly planning cycle, the CEJST development team could estimate the amount of time (in developer-weeks) that it would take to clean, analyze, and incorporate each potential data set. For instance, incorporating some already-cleaned census data may take 1 week of a developer's time, while incorporating new asthma data from CMS that's never been publicly released could take 5 weeks. Given a "budget" of the number of developer weeks available (e.g., 2 developers for 13 weeks, or 26 developer-weeks), advisors can vote on their top priorities for inclusion in the tool within the available "budget".

**Links to user research or other resources**
https://pbstanford.org/

**Tasks**
- [ ] Implement voting system of some sort
- [ ] Implement some notion of "budget" 

**Definition of "Done"**
- [ ] All community members have a publicly-available means of voting on datasets
