### ISSUE TITLE
As a J40 team member, I want to experiment with different ways to combine scores, so that we can arrive at a meaningful aggregate

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#55]
**Description**
There are a number of methodologies out there for combining scores into a single indicator - let's understand this a bit better and incorporate them into a proof of concept tool. We want to do a spike on the research for this to create a methodology we can begin doing user research with in our MURT.

**Solution**
Research, consult, make initial decision

**Describe alternatives you've considered**
This research will include an analysis of various scoring methods

**Links to user research or other resources**

**Tasks**
- [ ] Solicit community and expert feedback
- [ ] Identify a methodology to begin with for user feedback
- [ ] Document or implement this methodology in a non-UI tool (eg in a data notebook or as a command line tool)
- [ ] Test this methodology to ensure it is always consistent 

**Definition of "Done"**
- [ ] We have chosen an initial scoring methodology for user feedback in the MURT
- [ ] We have incorporated the score into our non-UI tool

**Comment by switzersc-usds** [comment]
Breaking this up into smaller cards.
