### ISSUE TITLE
As a developer, I want to ingest data from the Bureau of Indian Affairs that identifies federally recognized tribal lands, so that all census block groups on tribal lands can be identified

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#553]
**Description**
The Bureau of Indian Affairs (BIA) maintains a map of federally recognized tribal lands. While this data set is known to be incomplete, it would be a good starting point for identifying tribal lands on the screening tool map and for identifying census block groups that are on tribal lands.

The source of the BIA data:
https://biamaps.doi.gov/bogs/datadownload.html
Map:
](https://biamaps.doi.gov/indianlands/#)

**Tasks**
- [ ]  Obtain BIA data files
- [ ]  Import the data 
- [ ] Associated census block groups with tribal lands where applicable

**Definition of "Done"**
- [ ] BIA data at the census block group level is applied to census block groups so that it is available to be used by the screening tool
- [ ] BIA data is available to be displayed in the map UI
- [ ] BIA data is available to be downloaded in the CSV
