### ISSUE TITLE
As a repo contributor, I want to make sure my data processing code passes checks before/after it is merged, so that we maintain a high standard of quality and consistency

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#57]
**Description**
We should implement the best practices of continuous integration of source code, meaning performing the following checks for PRs against our data processing scripts (assumed at this stage to be python-based)
* Linting/formatting (eg `Black`, `flake8`) (potentially pre-commit hook?)
* Security auditing (eg `safety`)
* License check (eg `liccheck2`)
* Dependency updating (eg dependabot etc)
* Container-based unit testing / reporting (eg `unittest`, `pytest`, etc)
* Integration testing (e.g. `pytest` etc)
* Package management (e.g. `poetry`) 

**Solution**
Set up minimal pipelines with a chosen CI tool such as Github Actions/Jenkins/TravisCI that implement the above checks, targeting data processing filepaths

**Describe alternatives you've considered**
The alternative is to not perform these checks, which can lead to ruin.

**Links to user research or other resources**
N/A

**Tasks**
- [ ] Standup basic CI/CD for commits
- [ ] Add the above checks
- [ ] Determine the minimal set of necessary checks out of the gate and potentially create followup issues for the rest

**Definition of "Done"**
- [ ] Checks run on every PR against data processing scripts
- [ ] We have identified a basic set of tests that run on every PR / Commit and these are running regularly and producing results

**Comment by lucasmbrown-usds** [comment]
I really love `precommit`, is that something we'd consider using here?

**Comment by widal001** [comment]
@NatHillardUSDS Do you need any help with this? I've set up a fair amount of this basic infrastructure for my own Python projects and am a staunch advocate for having a solid testing framework in place haha.

If it would be helpful to jump on this, I had a few questions before creating a branch for the issue on my forked repo and chipping away at these items: 

- Will all Python code be stored within the `data-roadmap/` directory? Or do we expect there to be some elsewhere in the project, like in `server/` or future directories created for ETL scripts, etc.?
- If Python code is likely to be localized in `data-roadmap/` would you prefer to set up most of the config files for the checks and for unit/integration testing within that directory or at root?
- Would it be helpful to start work on this issue by drafting an architecture decision document (or documents) for the choices of libraries used for each of these checks? 
- If so, would it be helpful to submit a PR after drafting those docs, then mark the PR as "draft" to indicate that I'm looking for feedback, but not ready to merge the code directly?
- Finally, would this issue include writing unit tests for the existing functions in the `data-roadmap/utils/` modules or would that be scoped into a future issue?

**Comment by switzersc-usds** [comment]
Hi @widal001 ! Thanks for the offer to help and the good questions. Answers inline below:

> Will all Python code be stored within the data-roadmap/ directory? Or do we expect there to be some elsewhere in the project, like in server/ or future directories created for ETL scripts, etc.?

We'll probably want to store python and other data/ETL pipeline related code in a dedicated directory. `data-roadmap` holds more of the process and infrastructure for that process and the backlog of data ideas and datasets being investigated. We can create a `data-pipeline` directory for data/ETL pipeline related code and go with that. It's also likely that we'll want to support R or other languages for data processing, not just python. One more note here is that if we ever move away from a mono repo and separate the data pieces out, we'll likely have a data-pipeline repo that itself would include the `data-roadmap` work. 

> If Python code is likely to be localized in data-roadmap/ would you prefer to set up most of the config files for the checks and for unit/integration testing within that directory or at root?

Yes to setting up config in the root of the `data-pipeline` directory.

> Would it be helpful to start work on this issue by drafting an architecture decision document (or documents) for the choices of libraries used for each of these checks?

I think having an ADR for dependencies like this is a bit too heavy and would normally opt to put reasoning in the commit message that adds it. I feel like many of these libraries are pretty interchangeable and the decision isn't consequential enough to warrant a fleshed out ADR. Definitely feel free to disagree though, especially as we did say dependencies are the types of things we will have ADRs for.

> If so, would it be helpful to submit a PR after drafting those docs, then mark the PR as "draft" to indicate that I'm looking for feedback, but not ready to merge the code directly?

This makes sense to me. We should document this process and the use of labels. 

> Finally, would this issue include writing unit tests for the existing functions in the data-roadmap/utils/ modules or would that be scoped into a future issue?

Ah, I don't know if it's worth writing tests for things that won't live in a production environment. I would say no here.

We are looking to start setting up the data pipeline infrastructure in the next week or two, using the Census TIGER data and geoplatform.gov. If you'd like to get ahead and submit a draft PR setting up a data-pipeline directory and some basic python CI/CD checks, that would be awesome!

**Comment by widal001** [comment]
@switzersc-usds Thanks for answering these questions! I'll start working on a branch for this tonight with the goal of submitting a draft PR by Friday. 

One follow-up question to your responses above: If I create a new `data-pipeline/` directory with this setup, what do we want to do with the existing python scripts in `data-roadmap/` that it looks like @lucasmbrown-usds might have created in PR #34? Should those get moved into the new `data-pipeline/` directory or do we want to treat `data-roadmap/` as a separate package altogether?
