### ISSUE TITLE
As a contributor to J40, I want to have a "wizard" for ingesting new data, so that I can adhere to project standards for ETL classes.

### ISSUE THREAD

**Issue by widal001** [usds/justice40-tool#576]
## Description
As we encourage open source contributors to build ETL pipelines for new data sources, we want to simplify the process of creating the necessary modules and classes, and to ensure that the code they are contributing adheres to existing project standards and conventions within the `data_pipeline` package. The current process for setting up a new ETL class is fairly straightforward and much of the code from other modules in the `data_pipleine/etl/sources/` subdirectory can be reused, but those steps aren't immediately clear or easy to follow unless someone is already familiar with the existing code base. 

## Solution
Use the `click` python package to create a wizard-like command line interface (CLI) for setting up an ETL pipeline to ingest a new data source. The script triggered by this CLI command should automate most of the basic set up required to create an ETL class for a new data source and have that ETL class be picked up by the existing `etl-run` CLI command in `application.py` The instructions to create a new ETL pipeline using this CLI command should also be added to the `data-pipeline/README.md` 

## Describe alternatives you've considered

- **Only adding instructions to the README:** Necessary but not sufficient. Still requires contributors to take several steps in setting up the ETL process and could result in errors or inconsistencies.
- **Creating a `etl/sources/template/` module for contributors to copy:** Still a manual process and doesn't capture all of the steps needed for `etl/runner.py` to pick up and execute the new class

## Tasks
- [ ] Create a CLI command called `etl-source-init` in `application.py` which accepts the name of the new data source as a parameter and then automates the following steps: 
  - [ ] **ETL Source Directory:** Creates a new directory under `etl/sources/` with the snake case of the data source name, e.g. `National Risk Index` creates `etl/sources/national_risk_index/` 
  - [ ] **ETL Module:** Creates an `etl.py` module under the source directory with the scaffolding of a new ETL class that has the data source name in camel case and inherits from the `ExtractTransformLoad` base class, example:
  ```python
  class NationalRiskIndexETL(ExtractTransformLoad):
      def __init__(self):
          pass
      def extract(self):
         pass
      def transform(self):
         pass
      def load(self):
         pass
  ```
  - [ ]  **Test Directory:** Creates a test directory that mirrors the ETL Source Directory naming convention under `etl/tests/` and has the following contents:
    - [ ] `test_etl.py`
    - [ ] `data/input.csv`
    - [ ] `data/output.csv`
  - [ ] **ETL Runner:** Adds the name of the module directory and ETL class to the `DATASET_LIST` dictionary in `constants.py`
- [ ] Add instructions for how to set up a new ETL pipeline for an additional data source using the CLI command to `data-pipeline/README.md`

## Definition of "Done"
- [ ] A contributor can understand how to add a new dataset by following the instructions in `data-pipeline/README.md`
- [ ] A contributor can run one of the following commands in the command line to initialize an ETL pipeline for a new data source, and it will trigger a script that automates all of the steps listed above.
  - [ ] With Docker: `docker exec j40_data_pipeline_1 python3 -m data_pipeline.application etl-source-init`
  - [ ] With Poetry: `poetry run etl_source_init`
