### ISSUE TITLE
As a stakeholder, I want to see useful outputs from the comparison tool so that I can mak more informed decisions.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#608]
**Description**

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Shelby to share with team the current outputs of comparison tool
- [ ] Targeted team conversation about current feasibility for change ideas
- [ ] User research to identify some key changes (eg ask CM, watch their process for comparing data)
- [ ] Design creates rough sketches for team discussion
- [ ] Targeted team convo about proposed changes and create issues with estimations for this Epic

**Definition of "Done"**
