### ISSUE TITLE
As an EVCM, I want to make sure the information I see on the CEJST app matches what I see on the ground, so that I can trust that it represents the ground truth, or at least help it be more accurate

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#61]
**Description**
CEJST needs to reflect community members' lived experiences. We need a multi-pronged approach. One major part of the approach includes EJ community members co-designing tool and cumulative impact score through written recos, listening sessions, moderated user research sessions, feedback links in the tool, etc. But an additional way is to incorporate very personalized localized on the ground information from users, such as GPS tagged photos of bad pollution emission. To further illustrate, an EVCM may see that other communities in their county are prioritized ahead of theirs in CEJST, but they can take a photo of bad exhaust emitted near their home, in contrast to blue skies everywhere else they can see. They can provide on the ground data showing pollution uniquely burdening their community that is not reflected in the tool.

(This feature is not MVP, but wanted to get on team's radar sooner rather than later. Has far reaching implications. Might warrant being an epic in itself.)  

**Solution**
From the Justice40 Discovery Sprint Report 

>In California, where they use cumulative impacts score, they spent countless hours on the ground with and in communities in order to ensure that burdens and other factors were being considered. In some cases, the research team who originally developed scoring methodology upon which their geospatial tool, CalEnviroScreen, was built, would go into communities with preliminary maps and “ground-truth” them, block-by-block allowing community members armed with cell phones to capture pictures and tracked GPS locations to redraw them to more accurately reflect their lived experiences.

One potentially feasible solution would be to ask CalEnviroScreen team if they have recent on the ground information that can be shared with us, and we can see if CEJST visual mapping and scoring accurately represents, and potentially get the team's advice as well.

**Describe alternatives you've considered**
We could potentially conduct these kind of spot checks ourselves, or ask interested and willing EJ community members to help us with providing on the ground information.

**Links to user research or other resources**
City 311 apps allow community members to upload GPS tagged photos of incidents, sidewalk cleaning, dumping issues, etc. https://apps.apple.com/us/app/sf311/id666635420 for the purposes of city departments remediating. This also creates a measurable traceable body of community generated information. 

**Tasks**
 - [ ] How would we even receive this information? CEJST visitor ability to upload photos, etc? 
 - [ ] Define and implement how would we ingest and store information, meta data, etc.
 - [ ] Define and implement logic to connect on the ground information to community, i.e. census block
 - [ ] Define and implement process of review/arbitration of on the ground information and how it impacts how community is represented in app visually and prioritized via cumulative impact score

**Definition of "Done"**
 - [ ] First pilot of community member upload of on the ground information and being shown how information impacts (or will impact) how their community is represented visually in the tool and in cumulative impact score
