### ISSUE TITLE
As a code maintainer, I want to be able to validate that the output of each source ETL class adheres to a standard contract, so that no additional transformation is needed to compare or utilize those outputs in the scoring module.

### ISSUE THREAD

**Issue by widal001** [usds/justice40-tool#617]
## Description
Currently there are several inconsistencies across the outputs of ETL classes in `etl/sources/`. For example: 
- Some outputs are written as a GeoJSON instead of as a csv file
- Some outputs are saved at the Census Tract level instead of at the Census Block Group Level
- Some outputs contain the Census Block Group FIPS code, but the column with that information is named something else
- Some outputs contain indicator columns that need to be renamed before they are used in the score

Because of these inconsistencies, the `ScoreETL` class needs to do a fair amount of standardization across these sources before it can combine and uses them in the score. As a result, we need a mechanism for testing and enforcing that source ETL classes produce outputs that adhere to a standard ETL contract.

## Solution
Create a series of methods on the `ExtractTransformLoad` base class that can be called by the source ETL classes that inherit from it which will help those classes standardize their ETL output and validate that the output adheres to the ETL contract.

## Tasks

- [ ] Create a series of class globals and attributes on `ExtractTransformLoad` class that can be used by each source ETL class and can be checked for compliance against the contract
  - [ ] `CENSUS_CSV` (class global) Used to read in the definitive list of Census Block Group FIPS codes from the census data
  - [ ] `self.NAME` (class attribute) Used to create output path and populate logger info
  - [ ] `self.SOURCE_URL` (class attribute) Used to extract source data in `self.extract()`
  - [ ] `self.OUTPUT_PATH` (class attribute) Location where output csv is written in `self.load()`
  - [ ] `self.SCORE_COLS` (class attribute) List of columns that will be used in the score and should appear in the output csv
  - [ ] `self.FIPS_CODES` (class attribute) Dataframe of Census Block Group FIPS codes used to standardize the columns in the output csv
- [ ] Create a private method `self._get_census_fips_codes()` which extracts the Census Block Group and Census Tract FIPS codes from the Census data and stores it in `self.FIPS_CODES`
- [ ] Create an `ExtractTransformLoad.validate_output()` method that can be optionally called to check the compliance of the output of ETL classes with the conditions below:
  - [ ] An output csv has been created in the `data/dataset/{data_source_name}` directory
  - [ ] The output csv has a column named `GEOID10` which stores the census block group FIPS code
  - [ ] The columns in the output csv include the fields that will be used in the score and the names of those columns match the value expected by the score.
  - [ ] The `GEOID10` column contains all of the Census block groups
- [ ] Update `NationalRiskIndexETL` to conform to the new contract enforced by `ExtractTransformLoad.validate_output()`

## Definition of "Done"

- [ ] ETL classes that inherit from the `ExtractTransformLoad` class can check that their output adheres to the ETL contract by running `super().validate_output()` 
- [ ] Running `NationalRiskIndexETL.validate_output()` will result in a passing check
