### ISSUE TITLE
As a developer, I want to limit the audience that sees new features, so that we can control the message and positioning of our tool

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#66]
**Description**
We should add some means of limiting the audience for new features, so as to control the visibility of in-progress work while also getting real users to use our software

**Solution**
Use feature flagging on in-progress work, control through an allow list

**Describe alternatives you've considered**
* LaunchDarkly - a very full-featured version of this from the private sector; is there an OS equivalent?
* Security through obscurity - only sharing the link to certain people is not wise, as the link will get out. 

**Tasks**
- [ ] Add a feature flagging mechanism
- [ ] Use this feature flag for a particular feature
- [ ] Setup an initial audience for the feature

**Definition of "Done"**
- [ ] We have released a feature to only a subset of our total audience

**Open Questions**
* What tool should we use, in keeping with our OSS bent?
* How should we control the allow list, given we don't have user logins?

**Comment by katherinedm-usds** [comment]
Super high priority. This capability buys team so much maneuverability to get things right.
