### ISSUE TITLE
Ingest the energy communities data set so that it can be included in the UI and communities of focus download file

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#734]
**Description**
Datasets associated with figures in the Initial Report to the President on Empowering Workers Through Revitalizing Energy Communities needs to be available in the screening tool so that it can be displayed in the UI and included for all census block groups in the csv/excel download file. 

The source for energy communities is https://edx.netl.doe.gov/dataset/datasets-for-iwg-report-on-energy-communities

Both the raw value and the value converted to percentiles for the entire country must be available in the tool.

**Tasks**
- [ ]  Obtain energy community data files
- [ ]  Import the data 
- [ ]  Apply data to all census block groups 

**Definition of "Done"**
- [ ] Energy communities at the census block group level is available to be used as an input into the score
- [ ] LEAD score is available to be displayed in the map UI
- [ ] LEAD score is available to be downloaded in the CSV
