### ISSUE TITLE
Task: Double-check translation team's Spanish translation 

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#887]
## Describe the task
State team provided Spanish translation for header, footer, About, Explore, and Vim incorporated. There might be slight improvements to their translation that we would want to make and also highlight to that team so they can be aware of in the future, in particular when we kick them off on Data & methodology and Contact translation.

## Subtasks
- [ ] Review header in /es
- [ ] Review footer in /es
- [ ] Review About in /es
- [ ] Review Explore in /es
- [ ] List proposed improvements

## Additional context
Improvements @esfoobar-usds already identified

1. Header (but please confirm/correct capitalization)

> Justicia climática y económica
> Herramienta de evaluación

should be 
> Herramienta de evaluación
> Justicia climática y económica

2. Footer

> Consejo sobre la Calidad del Medio Ambiente

should be 

> Consejo de Calidad Ambiental (CEQ)
