### ISSUE TITLE
Decision: As a developer, I want to decide on a frontend mapping library to use, so that we faithfully represent our project values and provide for user needs

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#9]
**Description**
We should analyze frontend mapping visualization libraries and decide on one that both represents our project values and provides for our user needs. 

**Solution**
Create an Action Decision Record to represent our decision and explains our reasoning.

**Describe alternatives you've considered**
An Analysis of Alternatives is a pretty similar idea, but not directly supported via CLI [tooling](https://github.com/npryce/adr-tools)

**Links to user research or other resources**
This will be informed by:
* Our existing [map tech comparison](https://docs.google.com/spreadsheets/d/1KxPSlNAWHjFVe-v7ILEww77PB88fjwuAuK-mbjKy2GA/edit#gid=588651224)
* This [mural](https://app.mural.co/t/natinc9691/m/natinc9691/1617896233680/81f69695757238778b068a9135988f058c77e2e7) going over alternative stacks

**Tasks**
- [x] Create an Architectural Decision Record about Frontend mapping librareis
- [x] Decide on initial frontend map visualization framework to use

**Definition of "Done"**
- [x] We've fully explored alternatives, given current understanding of requirements
- [x] We've arrived at a choice that makes sense for now
- [x] We've documented our findings

**Comment by mikelmaron** [comment]
@NatHillardUSDS @switzersc-usds I understand this is a done decision and my comments come late, but I still wanted to lay down some thoughts for the record, and suggest some aspect of the comparison which I'm not sure were captured. Also want to state again, I'm not impartial here as I work for Mapbox, but am aiming to share as neutrally as possible on this project.

I was surprised by the choice of OpenLayers, which may just reflect that I haven't been tracking it lately. It has a strong history, and good friends were instrumental in its development. However at some point a few years ago, it fell behind and out of favor for what web developers were looking for in a mapping library. It is full featured to a degree useful from a GIS point of view, but with the tradeoff of complexity for developers to grapple with. Things which are easy in other libraries may be very hard in OpenLayers. That said, I haven't been paid attention to it the past couple years, and things could have improved.

For the user experience, my impression has been that rendering and interaction is not as smooth in OL, and that some desired features may be clunky or very hard. It's not just about rendering a large number of features, but interacting with and changing a large number of features. For instance, [dynamically coloring the map based on different thresholds](https://github.com/usds/justice40-tool/issues/42) would be well implemented by dynamically re-rendering the map with new styling rules (called in Mapbox "data driven styles"). In [this demo](https://earthrise-media.github.io/justice-map/) you can see this when zoomed in and filtering by EJ index scores, the highlights on block groups updates dynamically. Without ability to use WebGL this is likely going to be slow. It looks like `ol-mapbox-style` allows for loading Mapbox styles base maps, but not sure there would be any possibility for interaction with the data in the tilesets beyond that.

Seems like the key reason for choosing OL over Mapbox GL JS was the license change that came with 2.0. I get that. Let me offer a couple perspectives. First, while 2.0 is proprietarily licensed, all of the code is still developed and inspectable on GitHub, and there's active engagement in the issue tracker etc. Second, previous versions remain under their same licensing, so you could also consider a build against the [1.13.0 release](https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.13.0). 

My overall suggestion is to look one step further at specific features and interactions that the Justice40 Map will need, and do tests for ease of implementation and experience of the result.

**Comment by switzersc-usds** [comment]
@mikelmaron - thanks for bringing this up and weighing in! This is a done decision for now, but one of the points of making this open source is so that we can get community input and utilize expertise in the community, and we have architectural decision records to document decisions as well as to document changes to decisions we may make later.
 
> Seems like the key reason for choosing OL over Mapbox GL JS was the license change that came with 2.0

Yes, this was a key reason, in addition to the reasons noted in the [ADR](https://github.com/usds/justice40-tool/blob/main/docs/decisions/0002-mapping-visualization-library.md#mapping-visualization-library). One of our values is defaulting to open, and we believe that anyone should be able to run our code locally for free without using proprietary software, paying money, or having to sign up for accounts on third party services. Using an earlier version of Mapbox GL JS, or potentially the open source fork of Mapbox GL JS called MapLibre, are good options that we’ve considered, but we have some concerns about using them. Those concerns for MapLibre are documented [here](https://github.com/usds/justice40-tool/blob/main/docs/decisions/0002-mapping-visualization-library.md#maplibre-gl-js). For using the earlier version of Mapbox GL JS, we are unclear on what community support going forward looks like, e.g. with security patches, and our understanding as well is there were significant performance improvements made between that version and later versions of the library.

> My overall suggestion is to look one step further at specific features and interactions that the Justice40 Map will need, and do tests for ease of implementation and experience of the result.

Completely agree. We’ve made the decision for now to go with OpenLayers, because it meets our needs now as we understand them and the software, but we may revisit this in the future as we continue to define user stories and uncover what’s required technically to meet user needs. As we iterate with user research we may revisit this decision and open up a new architectural decision proposal for comment.
