### ISSUE TITLE
As a backend developer, I want to be specific about who gets what version of our site, so that I can provide a stable but informative experience for all users

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#91]
## Description
We should add a means of differentiating **backend** content on our site to the different audiences that need to see it. 

## Solution
We need to add the following environments to our **backend** site, accessible via a simple mechanism:
* qa
* staging 
* production
* PR (this will just be the hash of a particular PR)

## Describe alternatives you've considered
* Feature flagging was ruled out for now as it was too expensive at this time (see [#66](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/66). 
* We could gate the entire site via username/password using Basic Auth via CloudFront, but this is a bit too time consuming as well and wouldn't quite match this

## Tasks
- [ ] Decide on and document a strategy around environments
- [ ] Align this strategy with the Frontend version of this ticket ([#90](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/90))
- [ ] Implement this via Github Actions

## Definition of "Done"
- You can query a different URL for each of the above environments and get back a different bucket's content

**Comment by switzersc-usds** [comment]
Do we need QA *and* staging environments, in addition to environments spun up from PR branches?

**Comment by NatHillardUSDS** [comment]
See comment over in FE [ticket](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/90)  - the more we can focus on continued forward progress / appropriate flagging the more we can avoid merge conflicts / long-standing branches
