### ISSUE TITLE
As an engineer I want to ensure that all data set YAML files are validated when new ones are added

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#96]
**Description**
We should create a means for engineer community members to suggest new ideas for a dataset, using tools familiar to them.

**Solution**
For schema validation, we will be using Yamale. This provides a lightweight schema and validator, and integrates nicely with GitHub actions.

If there's an improper format in any of the files, the schema validator will throw an error.

We will need to set this up to run automatically with each commit to any branch as part of CI/CD.

**Describe alternatives you've considered**
- The benefit of using a YAML file for this is that it's easy to subject changes to these files to peer review through the pull request process. This allows external collaborators from the open source community to submit suggested changes, which can be reviewed by the core CEJST team.

**Tasks**
- [ ] Integrate this process into Continuous Integration
- [ ] Create Github issue template to create new dataset suggestion

**Definition of "Done"**
- [ ] Pipeline has been run end to end on a new dataset, including CI integration
