### ISSUE TITLE
Add link arrow to external links

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#991]
## Libs
- https://trussworks.github.io/react-uswds/?path=/docs/components-typography-link--external-link
- https://designsystem.digital.gov/components/link/#link-preview

## Tasks
- [ ] Validate with design/ prod that we will have 3 link types; check living copy to make sure!
1. external links (new tab), 
2. internal nav-link, 
3. internal scroll-to link
- [ ] Make all links on site use LinkTypeWrapper (which implements any one of the 3 link types)
- [ ] Integrate truss or uswds lib link in LinkTypeWrapper. 
- [x] Delete LaunchLink component
- [x] CSS warning - move all SASS file to components.scss file and then call in globals. scss. The following resources:
- https://stackoverflow.com/questions/60858885/how-do-i-avoid-the-warning-chunk-styles-mini-css-extract-plugin-conflicting-o
- https://github.com/facebook/create-react-app/issues/5372
- https://github.com/facebook/create-react-app/issues/5372#issuecomment-561703332 (this guys spells it out) ❤️ 
- [ ] update tests
- [ ] update cypress tests

**Comment by katherinedm-usds** [comment]
@KameronKerger will note in living copy which links are external so @vim-usds can use the correct link type (part of USWDS)

[href^=http]:not([href*="designsystem.digital.gov"])::after {
    background: 0 0;
    background-color: currentColor;
    -webkit-mask: url(../img/usa-icons/launch.svg) no-repeat center/1.75ex 1.75ex;
    mask: url(../img/usa-icons/launch.svg) no-repeat center/1.75ex 1.75ex;

**Comment by KameronKerger** [comment]
external links now noted in living copy doc
